######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 28 19:05:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += map_tracker.h
SOURCES += main.cpp map_tracker.cpp
