/********************************************************************************
** Form generated from reading UI file 'catan_map.ui'
**
** Created: Sun Apr 22 20:56:08 2012
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CATAN_MAP_H
#define UI_CATAN_MAP_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_catan_map
{
public:
    QAction *actionWorks;
    QWidget *centralWidget;
    QLabel *image_label;
    QPushButton *pushSettle_01;
    QPushButton *pushSettle_09;
    QPushButton *pushSettle_08;
    QPushButton *pushSettle_04;
    QPushButton *pushSettle_13;
    QPushButton *pushSettle_05;
    QPushButton *pushSettle_06;
    QPushButton *pushSettle_14;
    QPushButton *pushSettle_02;
    QPushButton *pushSettle_10;
    QPushButton *pushSettle_03;
    QPushButton *pushSettle_15;
    QPushButton *pushSettle_07;
    QPushButton *pushSettle_11;
    QPushButton *pushSettle_12;
    QPushButton *pushSettle_23;
    QPushButton *pushSettle_17;
    QPushButton *pushSettle_18;
    QPushButton *pushSettle_21;
    QPushButton *pushSettle_19;
    QPushButton *pushSettle_20;
    QPushButton *pushSettle_16;
    QPushButton *pushSettle_26;
    QPushButton *pushSettle_24;
    QPushButton *pushSettle_25;
    QPushButton *pushSettle_22;
    QPushButton *pushSettle_34;
    QPushButton *pushSettle_28;
    QPushButton *pushSettle_29;
    QPushButton *pushSettle_31;
    QPushButton *pushSettle_30;
    QPushButton *pushSettle_32;
    QPushButton *pushSettle_33;
    QPushButton *pushSettle_27;
    QPushButton *pushSettle_35;
    QPushButton *pushSettle_36;
    QPushButton *pushSettle_37;
    QPushButton *pushSettle_38;
    QPushButton *pushSettle_40;
    QPushButton *pushSettle_41;
    QPushButton *pushSettle_43;
    QPushButton *pushSettle_46;
    QPushButton *pushSettle_47;
    QPushButton *pushSettle_39;
    QPushButton *pushSettle_45;
    QPushButton *pushSettle_42;
    QPushButton *pushSettle_44;
    QPushButton *pushSettle_53;
    QPushButton *pushSettle_54;
    QPushButton *pushSettle_51;
    QPushButton *pushSettle_50;
    QPushButton *pushSettle_52;
    QPushButton *pushSettle_48;
    QPushButton *pushSettle_49;
    QPushButton *pushRoad_07;
    QPushButton *pushRoad_08;
    QPushButton *pushRoad_34;
    QPushButton *pushRoad_35;
    QPushButton *pushRoad_63;
    QPushButton *pushRoad_36;
    QPushButton *pushRoad_64;
    QPushButton *pushRoad_37;
    QPushButton *pushRoad_65;
    QPushButton *pushRoad_23;
    QPushButton *pushRoad_54;
    QPushButton *pushRoad_39;
    QPushButton *pushRoad_66;
    QPushButton *pushRoad_38;
    QPushButton *pushRoad_10;
    QPushButton *pushRoad_09;
    QPushButton *pushRoad_22;
    QPushButton *pushRoad_53;
    QPushButton *pushRoad_21;
    QPushButton *pushRoad_52;
    QPushButton *pushRoad_51;
    QPushButton *pushRoad_50;
    QPushButton *pushRoad_20;
    QPushButton *pushRoad_19;
    QPushButton *pushRoad_04;
    QPushButton *pushRoad_15;
    QPushButton *pushRoad_16;
    QPushButton *pushRoad_17;
    QPushButton *pushRoad_02;
    QPushButton *pushRoad_06;
    QPushButton *pushRoad_05;
    QPushButton *pushRoad_03;
    QPushButton *pushRoad_01;
    QPushButton *pushRoad_31;
    QPushButton *pushRoad_32;
    QPushButton *pushRoad_18;
    QPushButton *pushRoad_11;
    QPushButton *pushRoad_12;
    QPushButton *pushRoad_13;
    QPushButton *pushRoad_14;
    QPushButton *pushRoad_72;
    QPushButton *pushRoad_56;
    QPushButton *pushRoad_57;
    QPushButton *pushRoad_58;
    QPushButton *pushRoad_59;
    QPushButton *pushRoad_60;
    QPushButton *pushRoad_61;
    QPushButton *pushRoad_67;
    QPushButton *pushRoad_68;
    QPushButton *pushRoad_69;
    QPushButton *pushRoad_70;
    QPushButton *pushRoad_71;
    QPushButton *pushRoad_44;
    QPushButton *pushRoad_45;
    QPushButton *pushRoad_46;
    QPushButton *pushRoad_47;
    QPushButton *pushRoad_48;
    QPushButton *pushRoad_55;
    QPushButton *pushRoad_62;
    QPushButton *pushRoad_28;
    QPushButton *pushRoad_27;
    QPushButton *pushRoad_26;
    QPushButton *pushRoad_25;
    QPushButton *pushRoad_24;
    QPushButton *pushRoad_40;
    QPushButton *pushRoad_41;
    QPushButton *pushRoad_42;
    QPushButton *pushRoad_43;
    QPushButton *pushRoad_33;
    QPushButton *pushRoad_30;
    QPushButton *pushRoad_29;
    QPushButton *pushRoad_49;
    QFrame *frame;
    QLabel *player1_label;
    QLabel *color1_label;
    QLabel *victoryPnts1;
    QLabel *cardsHeld1_label;
    QPushButton *vhandButton_01;
    QLabel *instruction;
    QPushButton *rollButton;
    QLabel *roll_outcome;
    QPushButton *buyDevButton;
    QFrame *frame_2;
    QLabel *player2_label;
    QLabel *color2_label;
    QLabel *victoryPnts2;
    QLabel *cardsHeld2_label;
    QPushButton *vhandButton_02;
    QFrame *frame_3;
    QLabel *player3_label;
    QLabel *color3_label;
    QLabel *victoryPnts3;
    QLabel *cardsHeld3_label;
    QPushButton *vhandButton_03;
    QFrame *frame_4;
    QLabel *player4_label;
    QLabel *color4_label;
    QLabel *victoryPnts4;
    QLabel *cardsHeld4_label;
    QPushButton *vhandButton_04;
    QMenuBar *menuBar;
    QMenu *menuSample;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *catan_map)
    {
        if (catan_map->objectName().isEmpty())
            catan_map->setObjectName(QString::fromUtf8("catan_map"));
        catan_map->resize(1000, 703);
        actionWorks = new QAction(catan_map);
        actionWorks->setObjectName(QString::fromUtf8("actionWorks"));
        centralWidget = new QWidget(catan_map);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        image_label = new QLabel(centralWidget);
        image_label->setObjectName(QString::fromUtf8("image_label"));
        image_label->setGeometry(QRect(10, 0, 691, 600));
        pushSettle_01 = new QPushButton(centralWidget);
        pushSettle_01->setObjectName(QString::fromUtf8("pushSettle_01"));
        pushSettle_01->setGeometry(QRect(230, 30, 21, 21));
        pushSettle_09 = new QPushButton(centralWidget);
        pushSettle_09->setObjectName(QString::fromUtf8("pushSettle_09"));
        pushSettle_09->setGeometry(QRect(288, 128, 21, 21));
        pushSettle_08 = new QPushButton(centralWidget);
        pushSettle_08->setObjectName(QString::fromUtf8("pushSettle_08"));
        pushSettle_08->setGeometry(QRect(175, 128, 21, 21));
        pushSettle_04 = new QPushButton(centralWidget);
        pushSettle_04->setObjectName(QString::fromUtf8("pushSettle_04"));
        pushSettle_04->setGeometry(QRect(175, 68, 21, 21));
        pushSettle_13 = new QPushButton(centralWidget);
        pushSettle_13->setObjectName(QString::fromUtf8("pushSettle_13"));
        pushSettle_13->setGeometry(QRect(230, 162, 21, 21));
        pushSettle_05 = new QPushButton(centralWidget);
        pushSettle_05->setObjectName(QString::fromUtf8("pushSettle_05"));
        pushSettle_05->setGeometry(QRect(288, 68, 21, 21));
        pushSettle_06 = new QPushButton(centralWidget);
        pushSettle_06->setObjectName(QString::fromUtf8("pushSettle_06"));
        pushSettle_06->setGeometry(QRect(401, 68, 21, 21));
        pushSettle_14 = new QPushButton(centralWidget);
        pushSettle_14->setObjectName(QString::fromUtf8("pushSettle_14"));
        pushSettle_14->setGeometry(QRect(343, 162, 21, 21));
        pushSettle_02 = new QPushButton(centralWidget);
        pushSettle_02->setObjectName(QString::fromUtf8("pushSettle_02"));
        pushSettle_02->setGeometry(QRect(343, 30, 21, 21));
        pushSettle_10 = new QPushButton(centralWidget);
        pushSettle_10->setObjectName(QString::fromUtf8("pushSettle_10"));
        pushSettle_10->setGeometry(QRect(401, 128, 21, 21));
        pushSettle_03 = new QPushButton(centralWidget);
        pushSettle_03->setObjectName(QString::fromUtf8("pushSettle_03"));
        pushSettle_03->setGeometry(QRect(456, 30, 21, 21));
        pushSettle_15 = new QPushButton(centralWidget);
        pushSettle_15->setObjectName(QString::fromUtf8("pushSettle_15"));
        pushSettle_15->setGeometry(QRect(456, 162, 21, 21));
        pushSettle_07 = new QPushButton(centralWidget);
        pushSettle_07->setObjectName(QString::fromUtf8("pushSettle_07"));
        pushSettle_07->setGeometry(QRect(514, 68, 21, 21));
        pushSettle_11 = new QPushButton(centralWidget);
        pushSettle_11->setObjectName(QString::fromUtf8("pushSettle_11"));
        pushSettle_11->setGeometry(QRect(514, 128, 21, 21));
        pushSettle_12 = new QPushButton(centralWidget);
        pushSettle_12->setObjectName(QString::fromUtf8("pushSettle_12"));
        pushSettle_12->setGeometry(QRect(117, 162, 21, 21));
        pushSettle_23 = new QPushButton(centralWidget);
        pushSettle_23->setObjectName(QString::fromUtf8("pushSettle_23"));
        pushSettle_23->setGeometry(QRect(175, 260, 21, 21));
        pushSettle_17 = new QPushButton(centralWidget);
        pushSettle_17->setObjectName(QString::fromUtf8("pushSettle_17"));
        pushSettle_17->setGeometry(QRect(117, 222, 21, 21));
        pushSettle_18 = new QPushButton(centralWidget);
        pushSettle_18->setObjectName(QString::fromUtf8("pushSettle_18"));
        pushSettle_18->setGeometry(QRect(230, 222, 21, 21));
        pushSettle_21 = new QPushButton(centralWidget);
        pushSettle_21->setObjectName(QString::fromUtf8("pushSettle_21"));
        pushSettle_21->setGeometry(QRect(569, 222, 21, 21));
        pushSettle_19 = new QPushButton(centralWidget);
        pushSettle_19->setObjectName(QString::fromUtf8("pushSettle_19"));
        pushSettle_19->setGeometry(QRect(343, 222, 21, 21));
        pushSettle_20 = new QPushButton(centralWidget);
        pushSettle_20->setObjectName(QString::fromUtf8("pushSettle_20"));
        pushSettle_20->setGeometry(QRect(456, 222, 21, 21));
        pushSettle_16 = new QPushButton(centralWidget);
        pushSettle_16->setObjectName(QString::fromUtf8("pushSettle_16"));
        pushSettle_16->setGeometry(QRect(569, 162, 21, 21));
        pushSettle_26 = new QPushButton(centralWidget);
        pushSettle_26->setObjectName(QString::fromUtf8("pushSettle_26"));
        pushSettle_26->setGeometry(QRect(514, 260, 21, 21));
        pushSettle_24 = new QPushButton(centralWidget);
        pushSettle_24->setObjectName(QString::fromUtf8("pushSettle_24"));
        pushSettle_24->setGeometry(QRect(288, 260, 21, 21));
        pushSettle_25 = new QPushButton(centralWidget);
        pushSettle_25->setObjectName(QString::fromUtf8("pushSettle_25"));
        pushSettle_25->setGeometry(QRect(401, 260, 21, 21));
        pushSettle_22 = new QPushButton(centralWidget);
        pushSettle_22->setObjectName(QString::fromUtf8("pushSettle_22"));
        pushSettle_22->setGeometry(QRect(62, 260, 21, 21));
        pushSettle_34 = new QPushButton(centralWidget);
        pushSettle_34->setObjectName(QString::fromUtf8("pushSettle_34"));
        pushSettle_34->setGeometry(QRect(117, 354, 21, 21));
        pushSettle_28 = new QPushButton(centralWidget);
        pushSettle_28->setObjectName(QString::fromUtf8("pushSettle_28"));
        pushSettle_28->setGeometry(QRect(62, 320, 21, 21));
        pushSettle_29 = new QPushButton(centralWidget);
        pushSettle_29->setObjectName(QString::fromUtf8("pushSettle_29"));
        pushSettle_29->setGeometry(QRect(175, 320, 21, 21));
        pushSettle_31 = new QPushButton(centralWidget);
        pushSettle_31->setObjectName(QString::fromUtf8("pushSettle_31"));
        pushSettle_31->setGeometry(QRect(401, 320, 21, 21));
        pushSettle_30 = new QPushButton(centralWidget);
        pushSettle_30->setObjectName(QString::fromUtf8("pushSettle_30"));
        pushSettle_30->setGeometry(QRect(288, 320, 21, 21));
        pushSettle_32 = new QPushButton(centralWidget);
        pushSettle_32->setObjectName(QString::fromUtf8("pushSettle_32"));
        pushSettle_32->setGeometry(QRect(514, 320, 21, 21));
        pushSettle_33 = new QPushButton(centralWidget);
        pushSettle_33->setObjectName(QString::fromUtf8("pushSettle_33"));
        pushSettle_33->setGeometry(QRect(627, 320, 21, 21));
        pushSettle_27 = new QPushButton(centralWidget);
        pushSettle_27->setObjectName(QString::fromUtf8("pushSettle_27"));
        pushSettle_27->setGeometry(QRect(627, 260, 21, 21));
        pushSettle_35 = new QPushButton(centralWidget);
        pushSettle_35->setObjectName(QString::fromUtf8("pushSettle_35"));
        pushSettle_35->setGeometry(QRect(230, 354, 21, 21));
        pushSettle_36 = new QPushButton(centralWidget);
        pushSettle_36->setObjectName(QString::fromUtf8("pushSettle_36"));
        pushSettle_36->setGeometry(QRect(343, 354, 21, 21));
        pushSettle_37 = new QPushButton(centralWidget);
        pushSettle_37->setObjectName(QString::fromUtf8("pushSettle_37"));
        pushSettle_37->setGeometry(QRect(456, 354, 21, 21));
        pushSettle_38 = new QPushButton(centralWidget);
        pushSettle_38->setObjectName(QString::fromUtf8("pushSettle_38"));
        pushSettle_38->setGeometry(QRect(569, 354, 21, 21));
        pushSettle_40 = new QPushButton(centralWidget);
        pushSettle_40->setObjectName(QString::fromUtf8("pushSettle_40"));
        pushSettle_40->setGeometry(QRect(230, 414, 21, 21));
        pushSettle_41 = new QPushButton(centralWidget);
        pushSettle_41->setObjectName(QString::fromUtf8("pushSettle_41"));
        pushSettle_41->setGeometry(QRect(343, 414, 21, 21));
        pushSettle_43 = new QPushButton(centralWidget);
        pushSettle_43->setObjectName(QString::fromUtf8("pushSettle_43"));
        pushSettle_43->setGeometry(QRect(569, 414, 21, 21));
        pushSettle_46 = new QPushButton(centralWidget);
        pushSettle_46->setObjectName(QString::fromUtf8("pushSettle_46"));
        pushSettle_46->setGeometry(QRect(401, 452, 21, 21));
        pushSettle_47 = new QPushButton(centralWidget);
        pushSettle_47->setObjectName(QString::fromUtf8("pushSettle_47"));
        pushSettle_47->setGeometry(QRect(514, 452, 21, 21));
        pushSettle_39 = new QPushButton(centralWidget);
        pushSettle_39->setObjectName(QString::fromUtf8("pushSettle_39"));
        pushSettle_39->setGeometry(QRect(117, 414, 21, 21));
        pushSettle_45 = new QPushButton(centralWidget);
        pushSettle_45->setObjectName(QString::fromUtf8("pushSettle_45"));
        pushSettle_45->setGeometry(QRect(288, 452, 21, 21));
        pushSettle_42 = new QPushButton(centralWidget);
        pushSettle_42->setObjectName(QString::fromUtf8("pushSettle_42"));
        pushSettle_42->setGeometry(QRect(456, 414, 21, 21));
        pushSettle_44 = new QPushButton(centralWidget);
        pushSettle_44->setObjectName(QString::fromUtf8("pushSettle_44"));
        pushSettle_44->setGeometry(QRect(175, 452, 21, 21));
        pushSettle_53 = new QPushButton(centralWidget);
        pushSettle_53->setObjectName(QString::fromUtf8("pushSettle_53"));
        pushSettle_53->setGeometry(QRect(343, 546, 21, 21));
        pushSettle_54 = new QPushButton(centralWidget);
        pushSettle_54->setObjectName(QString::fromUtf8("pushSettle_54"));
        pushSettle_54->setGeometry(QRect(456, 546, 21, 21));
        pushSettle_51 = new QPushButton(centralWidget);
        pushSettle_51->setObjectName(QString::fromUtf8("pushSettle_51"));
        pushSettle_51->setGeometry(QRect(514, 512, 21, 21));
        pushSettle_50 = new QPushButton(centralWidget);
        pushSettle_50->setObjectName(QString::fromUtf8("pushSettle_50"));
        pushSettle_50->setGeometry(QRect(401, 512, 21, 21));
        pushSettle_52 = new QPushButton(centralWidget);
        pushSettle_52->setObjectName(QString::fromUtf8("pushSettle_52"));
        pushSettle_52->setGeometry(QRect(230, 546, 21, 21));
        pushSettle_48 = new QPushButton(centralWidget);
        pushSettle_48->setObjectName(QString::fromUtf8("pushSettle_48"));
        pushSettle_48->setGeometry(QRect(175, 512, 21, 21));
        pushSettle_49 = new QPushButton(centralWidget);
        pushSettle_49->setObjectName(QString::fromUtf8("pushSettle_49"));
        pushSettle_49->setGeometry(QRect(288, 512, 21, 21));
        pushRoad_07 = new QPushButton(centralWidget);
        pushRoad_07->setObjectName(QString::fromUtf8("pushRoad_07"));
        pushRoad_07->setGeometry(QRect(175, 93, 21, 31));
        pushRoad_08 = new QPushButton(centralWidget);
        pushRoad_08->setObjectName(QString::fromUtf8("pushRoad_08"));
        pushRoad_08->setGeometry(QRect(288, 93, 21, 31));
        pushRoad_34 = new QPushButton(centralWidget);
        pushRoad_34->setObjectName(QString::fromUtf8("pushRoad_34"));
        pushRoad_34->setGeometry(QRect(62, 285, 21, 31));
        pushRoad_35 = new QPushButton(centralWidget);
        pushRoad_35->setObjectName(QString::fromUtf8("pushRoad_35"));
        pushRoad_35->setGeometry(QRect(175, 285, 21, 31));
        pushRoad_63 = new QPushButton(centralWidget);
        pushRoad_63->setObjectName(QString::fromUtf8("pushRoad_63"));
        pushRoad_63->setGeometry(QRect(175, 477, 21, 31));
        pushRoad_36 = new QPushButton(centralWidget);
        pushRoad_36->setObjectName(QString::fromUtf8("pushRoad_36"));
        pushRoad_36->setGeometry(QRect(288, 285, 21, 31));
        pushRoad_64 = new QPushButton(centralWidget);
        pushRoad_64->setObjectName(QString::fromUtf8("pushRoad_64"));
        pushRoad_64->setGeometry(QRect(288, 477, 21, 31));
        pushRoad_37 = new QPushButton(centralWidget);
        pushRoad_37->setObjectName(QString::fromUtf8("pushRoad_37"));
        pushRoad_37->setGeometry(QRect(401, 285, 21, 31));
        pushRoad_65 = new QPushButton(centralWidget);
        pushRoad_65->setObjectName(QString::fromUtf8("pushRoad_65"));
        pushRoad_65->setGeometry(QRect(401, 477, 21, 31));
        pushRoad_23 = new QPushButton(centralWidget);
        pushRoad_23->setObjectName(QString::fromUtf8("pushRoad_23"));
        pushRoad_23->setGeometry(QRect(569, 185, 21, 31));
        pushRoad_54 = new QPushButton(centralWidget);
        pushRoad_54->setObjectName(QString::fromUtf8("pushRoad_54"));
        pushRoad_54->setGeometry(QRect(569, 379, 21, 31));
        pushRoad_39 = new QPushButton(centralWidget);
        pushRoad_39->setObjectName(QString::fromUtf8("pushRoad_39"));
        pushRoad_39->setGeometry(QRect(627, 285, 21, 31));
        pushRoad_66 = new QPushButton(centralWidget);
        pushRoad_66->setObjectName(QString::fromUtf8("pushRoad_66"));
        pushRoad_66->setGeometry(QRect(514, 477, 21, 31));
        pushRoad_38 = new QPushButton(centralWidget);
        pushRoad_38->setObjectName(QString::fromUtf8("pushRoad_38"));
        pushRoad_38->setGeometry(QRect(514, 285, 21, 31));
        pushRoad_10 = new QPushButton(centralWidget);
        pushRoad_10->setObjectName(QString::fromUtf8("pushRoad_10"));
        pushRoad_10->setGeometry(QRect(514, 93, 21, 31));
        pushRoad_09 = new QPushButton(centralWidget);
        pushRoad_09->setObjectName(QString::fromUtf8("pushRoad_09"));
        pushRoad_09->setGeometry(QRect(401, 93, 21, 31));
        pushRoad_22 = new QPushButton(centralWidget);
        pushRoad_22->setObjectName(QString::fromUtf8("pushRoad_22"));
        pushRoad_22->setGeometry(QRect(456, 185, 21, 31));
        pushRoad_53 = new QPushButton(centralWidget);
        pushRoad_53->setObjectName(QString::fromUtf8("pushRoad_53"));
        pushRoad_53->setGeometry(QRect(456, 379, 21, 31));
        pushRoad_21 = new QPushButton(centralWidget);
        pushRoad_21->setObjectName(QString::fromUtf8("pushRoad_21"));
        pushRoad_21->setGeometry(QRect(343, 185, 21, 31));
        pushRoad_52 = new QPushButton(centralWidget);
        pushRoad_52->setObjectName(QString::fromUtf8("pushRoad_52"));
        pushRoad_52->setGeometry(QRect(343, 379, 21, 31));
        pushRoad_51 = new QPushButton(centralWidget);
        pushRoad_51->setObjectName(QString::fromUtf8("pushRoad_51"));
        pushRoad_51->setGeometry(QRect(230, 379, 21, 31));
        pushRoad_50 = new QPushButton(centralWidget);
        pushRoad_50->setObjectName(QString::fromUtf8("pushRoad_50"));
        pushRoad_50->setGeometry(QRect(117, 379, 21, 31));
        pushRoad_20 = new QPushButton(centralWidget);
        pushRoad_20->setObjectName(QString::fromUtf8("pushRoad_20"));
        pushRoad_20->setGeometry(QRect(230, 185, 21, 31));
        pushRoad_19 = new QPushButton(centralWidget);
        pushRoad_19->setObjectName(QString::fromUtf8("pushRoad_19"));
        pushRoad_19->setGeometry(QRect(117, 185, 21, 31));
        pushRoad_04 = new QPushButton(centralWidget);
        pushRoad_04->setObjectName(QString::fromUtf8("pushRoad_04"));
        pushRoad_04->setGeometry(QRect(373, 43, 21, 31));
        pushRoad_15 = new QPushButton(centralWidget);
        pushRoad_15->setObjectName(QString::fromUtf8("pushRoad_15"));
        pushRoad_15->setGeometry(QRect(373, 141, 21, 31));
        pushRoad_16 = new QPushButton(centralWidget);
        pushRoad_16->setObjectName(QString::fromUtf8("pushRoad_16"));
        pushRoad_16->setGeometry(QRect(426, 141, 21, 31));
        pushRoad_17 = new QPushButton(centralWidget);
        pushRoad_17->setObjectName(QString::fromUtf8("pushRoad_17"));
        pushRoad_17->setGeometry(QRect(486, 141, 21, 31));
        pushRoad_02 = new QPushButton(centralWidget);
        pushRoad_02->setObjectName(QString::fromUtf8("pushRoad_02"));
        pushRoad_02->setGeometry(QRect(260, 43, 21, 31));
        pushRoad_06 = new QPushButton(centralWidget);
        pushRoad_06->setObjectName(QString::fromUtf8("pushRoad_06"));
        pushRoad_06->setGeometry(QRect(486, 43, 21, 31));
        pushRoad_05 = new QPushButton(centralWidget);
        pushRoad_05->setObjectName(QString::fromUtf8("pushRoad_05"));
        pushRoad_05->setGeometry(QRect(426, 43, 21, 31));
        pushRoad_03 = new QPushButton(centralWidget);
        pushRoad_03->setObjectName(QString::fromUtf8("pushRoad_03"));
        pushRoad_03->setGeometry(QRect(313, 43, 21, 31));
        pushRoad_01 = new QPushButton(centralWidget);
        pushRoad_01->setObjectName(QString::fromUtf8("pushRoad_01"));
        pushRoad_01->setGeometry(QRect(200, 43, 21, 31));
        pushRoad_31 = new QPushButton(centralWidget);
        pushRoad_31->setObjectName(QString::fromUtf8("pushRoad_31"));
        pushRoad_31->setGeometry(QRect(486, 235, 21, 31));
        pushRoad_32 = new QPushButton(centralWidget);
        pushRoad_32->setObjectName(QString::fromUtf8("pushRoad_32"));
        pushRoad_32->setGeometry(QRect(544, 235, 21, 31));
        pushRoad_18 = new QPushButton(centralWidget);
        pushRoad_18->setObjectName(QString::fromUtf8("pushRoad_18"));
        pushRoad_18->setGeometry(QRect(544, 141, 21, 31));
        pushRoad_11 = new QPushButton(centralWidget);
        pushRoad_11->setObjectName(QString::fromUtf8("pushRoad_11"));
        pushRoad_11->setGeometry(QRect(145, 141, 21, 31));
        pushRoad_12 = new QPushButton(centralWidget);
        pushRoad_12->setObjectName(QString::fromUtf8("pushRoad_12"));
        pushRoad_12->setGeometry(QRect(200, 141, 21, 31));
        pushRoad_13 = new QPushButton(centralWidget);
        pushRoad_13->setObjectName(QString::fromUtf8("pushRoad_13"));
        pushRoad_13->setGeometry(QRect(260, 141, 21, 31));
        pushRoad_14 = new QPushButton(centralWidget);
        pushRoad_14->setObjectName(QString::fromUtf8("pushRoad_14"));
        pushRoad_14->setGeometry(QRect(313, 141, 21, 31));
        pushRoad_72 = new QPushButton(centralWidget);
        pushRoad_72->setObjectName(QString::fromUtf8("pushRoad_72"));
        pushRoad_72->setGeometry(QRect(486, 525, 21, 31));
        pushRoad_56 = new QPushButton(centralWidget);
        pushRoad_56->setObjectName(QString::fromUtf8("pushRoad_56"));
        pushRoad_56->setGeometry(QRect(200, 427, 21, 31));
        pushRoad_57 = new QPushButton(centralWidget);
        pushRoad_57->setObjectName(QString::fromUtf8("pushRoad_57"));
        pushRoad_57->setGeometry(QRect(260, 427, 21, 31));
        pushRoad_58 = new QPushButton(centralWidget);
        pushRoad_58->setObjectName(QString::fromUtf8("pushRoad_58"));
        pushRoad_58->setGeometry(QRect(313, 427, 21, 31));
        pushRoad_59 = new QPushButton(centralWidget);
        pushRoad_59->setObjectName(QString::fromUtf8("pushRoad_59"));
        pushRoad_59->setGeometry(QRect(373, 427, 21, 31));
        pushRoad_60 = new QPushButton(centralWidget);
        pushRoad_60->setObjectName(QString::fromUtf8("pushRoad_60"));
        pushRoad_60->setGeometry(QRect(426, 427, 21, 31));
        pushRoad_61 = new QPushButton(centralWidget);
        pushRoad_61->setObjectName(QString::fromUtf8("pushRoad_61"));
        pushRoad_61->setGeometry(QRect(486, 427, 21, 31));
        pushRoad_67 = new QPushButton(centralWidget);
        pushRoad_67->setObjectName(QString::fromUtf8("pushRoad_67"));
        pushRoad_67->setGeometry(QRect(200, 525, 21, 31));
        pushRoad_68 = new QPushButton(centralWidget);
        pushRoad_68->setObjectName(QString::fromUtf8("pushRoad_68"));
        pushRoad_68->setGeometry(QRect(260, 525, 21, 31));
        pushRoad_69 = new QPushButton(centralWidget);
        pushRoad_69->setObjectName(QString::fromUtf8("pushRoad_69"));
        pushRoad_69->setGeometry(QRect(313, 525, 21, 31));
        pushRoad_70 = new QPushButton(centralWidget);
        pushRoad_70->setObjectName(QString::fromUtf8("pushRoad_70"));
        pushRoad_70->setGeometry(QRect(373, 525, 21, 31));
        pushRoad_71 = new QPushButton(centralWidget);
        pushRoad_71->setObjectName(QString::fromUtf8("pushRoad_71"));
        pushRoad_71->setGeometry(QRect(426, 525, 21, 31));
        pushRoad_44 = new QPushButton(centralWidget);
        pushRoad_44->setObjectName(QString::fromUtf8("pushRoad_44"));
        pushRoad_44->setGeometry(QRect(313, 333, 21, 31));
        pushRoad_45 = new QPushButton(centralWidget);
        pushRoad_45->setObjectName(QString::fromUtf8("pushRoad_45"));
        pushRoad_45->setGeometry(QRect(373, 333, 21, 31));
        pushRoad_46 = new QPushButton(centralWidget);
        pushRoad_46->setObjectName(QString::fromUtf8("pushRoad_46"));
        pushRoad_46->setGeometry(QRect(426, 333, 21, 31));
        pushRoad_47 = new QPushButton(centralWidget);
        pushRoad_47->setObjectName(QString::fromUtf8("pushRoad_47"));
        pushRoad_47->setGeometry(QRect(486, 333, 21, 31));
        pushRoad_48 = new QPushButton(centralWidget);
        pushRoad_48->setObjectName(QString::fromUtf8("pushRoad_48"));
        pushRoad_48->setGeometry(QRect(544, 333, 21, 31));
        pushRoad_55 = new QPushButton(centralWidget);
        pushRoad_55->setObjectName(QString::fromUtf8("pushRoad_55"));
        pushRoad_55->setGeometry(QRect(145, 427, 21, 31));
        pushRoad_62 = new QPushButton(centralWidget);
        pushRoad_62->setObjectName(QString::fromUtf8("pushRoad_62"));
        pushRoad_62->setGeometry(QRect(544, 427, 21, 31));
        pushRoad_28 = new QPushButton(centralWidget);
        pushRoad_28->setObjectName(QString::fromUtf8("pushRoad_28"));
        pushRoad_28->setGeometry(QRect(313, 235, 21, 31));
        pushRoad_27 = new QPushButton(centralWidget);
        pushRoad_27->setObjectName(QString::fromUtf8("pushRoad_27"));
        pushRoad_27->setGeometry(QRect(260, 235, 21, 31));
        pushRoad_26 = new QPushButton(centralWidget);
        pushRoad_26->setObjectName(QString::fromUtf8("pushRoad_26"));
        pushRoad_26->setGeometry(QRect(200, 235, 21, 31));
        pushRoad_25 = new QPushButton(centralWidget);
        pushRoad_25->setObjectName(QString::fromUtf8("pushRoad_25"));
        pushRoad_25->setGeometry(QRect(145, 235, 21, 31));
        pushRoad_24 = new QPushButton(centralWidget);
        pushRoad_24->setObjectName(QString::fromUtf8("pushRoad_24"));
        pushRoad_24->setGeometry(QRect(87, 235, 21, 31));
        pushRoad_40 = new QPushButton(centralWidget);
        pushRoad_40->setObjectName(QString::fromUtf8("pushRoad_40"));
        pushRoad_40->setGeometry(QRect(87, 333, 21, 31));
        pushRoad_41 = new QPushButton(centralWidget);
        pushRoad_41->setObjectName(QString::fromUtf8("pushRoad_41"));
        pushRoad_41->setGeometry(QRect(145, 333, 21, 31));
        pushRoad_42 = new QPushButton(centralWidget);
        pushRoad_42->setObjectName(QString::fromUtf8("pushRoad_42"));
        pushRoad_42->setGeometry(QRect(200, 333, 21, 31));
        pushRoad_43 = new QPushButton(centralWidget);
        pushRoad_43->setObjectName(QString::fromUtf8("pushRoad_43"));
        pushRoad_43->setGeometry(QRect(260, 333, 21, 31));
        pushRoad_33 = new QPushButton(centralWidget);
        pushRoad_33->setObjectName(QString::fromUtf8("pushRoad_33"));
        pushRoad_33->setGeometry(QRect(599, 235, 21, 31));
        pushRoad_30 = new QPushButton(centralWidget);
        pushRoad_30->setObjectName(QString::fromUtf8("pushRoad_30"));
        pushRoad_30->setGeometry(QRect(426, 235, 21, 31));
        pushRoad_29 = new QPushButton(centralWidget);
        pushRoad_29->setObjectName(QString::fromUtf8("pushRoad_29"));
        pushRoad_29->setGeometry(QRect(373, 235, 21, 31));
        pushRoad_49 = new QPushButton(centralWidget);
        pushRoad_49->setObjectName(QString::fromUtf8("pushRoad_49"));
        pushRoad_49->setGeometry(QRect(599, 330, 21, 31));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(710, 3, 281, 141));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        player1_label = new QLabel(frame);
        player1_label->setObjectName(QString::fromUtf8("player1_label"));
        player1_label->setGeometry(QRect(10, 10, 101, 17));
        QFont font;
        font.setPointSize(16);
        player1_label->setFont(font);
        color1_label = new QLabel(frame);
        color1_label->setObjectName(QString::fromUtf8("color1_label"));
        color1_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts1 = new QLabel(frame);
        victoryPnts1->setObjectName(QString::fromUtf8("victoryPnts1"));
        victoryPnts1->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld1_label = new QLabel(frame);
        cardsHeld1_label->setObjectName(QString::fromUtf8("cardsHeld1_label"));
        cardsHeld1_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_01 = new QPushButton(frame);
        vhandButton_01->setObjectName(QString::fromUtf8("vhandButton_01"));
        vhandButton_01->setGeometry(QRect(60, 40, 131, 51));
        instruction = new QLabel(centralWidget);
        instruction->setObjectName(QString::fromUtf8("instruction"));
        instruction->setGeometry(QRect(40, 610, 601, 17));
        rollButton = new QPushButton(centralWidget);
        rollButton->setObjectName(QString::fromUtf8("rollButton"));
        rollButton->setGeometry(QRect(890, 604, 97, 27));
        roll_outcome = new QLabel(centralWidget);
        roll_outcome->setObjectName(QString::fromUtf8("roll_outcome"));
        roll_outcome->setGeometry(QRect(790, 610, 91, 17));
        buyDevButton = new QPushButton(centralWidget);
        buyDevButton->setObjectName(QString::fromUtf8("buyDevButton"));
        buyDevButton->setGeometry(QRect(610, 604, 171, 27));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(710, 150, 281, 141));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        player2_label = new QLabel(frame_2);
        player2_label->setObjectName(QString::fromUtf8("player2_label"));
        player2_label->setGeometry(QRect(10, 10, 101, 17));
        player2_label->setFont(font);
        color2_label = new QLabel(frame_2);
        color2_label->setObjectName(QString::fromUtf8("color2_label"));
        color2_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts2 = new QLabel(frame_2);
        victoryPnts2->setObjectName(QString::fromUtf8("victoryPnts2"));
        victoryPnts2->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld2_label = new QLabel(frame_2);
        cardsHeld2_label->setObjectName(QString::fromUtf8("cardsHeld2_label"));
        cardsHeld2_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_02 = new QPushButton(frame_2);
        vhandButton_02->setObjectName(QString::fromUtf8("vhandButton_02"));
        vhandButton_02->setGeometry(QRect(60, 40, 131, 51));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(710, 300, 281, 141));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        player3_label = new QLabel(frame_3);
        player3_label->setObjectName(QString::fromUtf8("player3_label"));
        player3_label->setGeometry(QRect(10, 10, 101, 17));
        player3_label->setFont(font);
        color3_label = new QLabel(frame_3);
        color3_label->setObjectName(QString::fromUtf8("color3_label"));
        color3_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts3 = new QLabel(frame_3);
        victoryPnts3->setObjectName(QString::fromUtf8("victoryPnts3"));
        victoryPnts3->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld3_label = new QLabel(frame_3);
        cardsHeld3_label->setObjectName(QString::fromUtf8("cardsHeld3_label"));
        cardsHeld3_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_03 = new QPushButton(frame_3);
        vhandButton_03->setObjectName(QString::fromUtf8("vhandButton_03"));
        vhandButton_03->setGeometry(QRect(60, 40, 131, 51));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(710, 450, 281, 141));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        player4_label = new QLabel(frame_4);
        player4_label->setObjectName(QString::fromUtf8("player4_label"));
        player4_label->setGeometry(QRect(10, 10, 101, 17));
        player4_label->setFont(font);
        color4_label = new QLabel(frame_4);
        color4_label->setObjectName(QString::fromUtf8("color4_label"));
        color4_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts4 = new QLabel(frame_4);
        victoryPnts4->setObjectName(QString::fromUtf8("victoryPnts4"));
        victoryPnts4->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld4_label = new QLabel(frame_4);
        cardsHeld4_label->setObjectName(QString::fromUtf8("cardsHeld4_label"));
        cardsHeld4_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_04 = new QPushButton(frame_4);
        vhandButton_04->setObjectName(QString::fromUtf8("vhandButton_04"));
        vhandButton_04->setGeometry(QRect(60, 40, 131, 51));
        catan_map->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(catan_map);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1000, 25));
        menuSample = new QMenu(menuBar);
        menuSample->setObjectName(QString::fromUtf8("menuSample"));
        catan_map->setMenuBar(menuBar);
        mainToolBar = new QToolBar(catan_map);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        catan_map->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(catan_map);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        catan_map->setStatusBar(statusBar);

        menuBar->addAction(menuSample->menuAction());
        menuSample->addAction(actionWorks);

        retranslateUi(catan_map);

        QMetaObject::connectSlotsByName(catan_map);
    } // setupUi

    void retranslateUi(QMainWindow *catan_map)
    {
        catan_map->setWindowTitle(QApplication::translate("catan_map", "catan_map", 0, QApplication::UnicodeUTF8));
        actionWorks->setText(QApplication::translate("catan_map", "Works!!", 0, QApplication::UnicodeUTF8));
        image_label->setText(QString());
        pushSettle_01->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_09->setText(QApplication::translate("catan_map", "16", 0, QApplication::UnicodeUTF8));
        pushSettle_08->setText(QApplication::translate("catan_map", "63", 0, QApplication::UnicodeUTF8));
        pushSettle_04->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_13->setText(QApplication::translate("catan_map", "62", 0, QApplication::UnicodeUTF8));
        pushSettle_05->setText(QApplication::translate("catan_map", "15", 0, QApplication::UnicodeUTF8));
        pushSettle_06->setText(QApplication::translate("catan_map", "13", 0, QApplication::UnicodeUTF8));
        pushSettle_14->setText(QApplication::translate("catan_map", "11", 0, QApplication::UnicodeUTF8));
        pushSettle_02->setText(QApplication::translate("catan_map", "14", 0, QApplication::UnicodeUTF8));
        pushSettle_10->setText(QApplication::translate("catan_map", "12", 0, QApplication::UnicodeUTF8));
        pushSettle_03->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_15->setText(QApplication::translate("catan_map", "26", 0, QApplication::UnicodeUTF8));
        pushSettle_07->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_11->setText(QApplication::translate("catan_map", "25", 0, QApplication::UnicodeUTF8));
        pushSettle_12->setText(QApplication::translate("catan_map", "64", 0, QApplication::UnicodeUTF8));
        pushSettle_23->setText(QApplication::translate("catan_map", "66", 0, QApplication::UnicodeUTF8));
        pushSettle_17->setText(QApplication::translate("catan_map", "65", 0, QApplication::UnicodeUTF8));
        pushSettle_18->setText(QApplication::translate("catan_map", "61", 0, QApplication::UnicodeUTF8));
        pushSettle_21->setText(QApplication::translate("catan_map", "23", 0, QApplication::UnicodeUTF8));
        pushSettle_19->setText(QApplication::translate("catan_map", "10", 0, QApplication::UnicodeUTF8));
        pushSettle_20->setText(QApplication::translate("catan_map", "21", 0, QApplication::UnicodeUTF8));
        pushSettle_16->setText(QApplication::translate("catan_map", "24", 0, QApplication::UnicodeUTF8));
        pushSettle_26->setText(QApplication::translate("catan_map", "22", 0, QApplication::UnicodeUTF8));
        pushSettle_24->setText(QApplication::translate("catan_map", "60", 0, QApplication::UnicodeUTF8));
        pushSettle_25->setText(QApplication::translate("catan_map", "20", 0, QApplication::UnicodeUTF8));
        pushSettle_22->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_34->setText(QApplication::translate("catan_map", "53", 0, QApplication::UnicodeUTF8));
        pushSettle_28->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_29->setText(QApplication::translate("catan_map", "52", 0, QApplication::UnicodeUTF8));
        pushSettle_31->setText(QApplication::translate("catan_map", "30", 0, QApplication::UnicodeUTF8));
        pushSettle_30->setText(QApplication::translate("catan_map", "50", 0, QApplication::UnicodeUTF8));
        pushSettle_32->setText(QApplication::translate("catan_map", "36", 0, QApplication::UnicodeUTF8));
        pushSettle_33->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_27->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_35->setText(QApplication::translate("catan_map", "51", 0, QApplication::UnicodeUTF8));
        pushSettle_36->setText(QApplication::translate("catan_map", "40", 0, QApplication::UnicodeUTF8));
        pushSettle_37->setText(QApplication::translate("catan_map", "31", 0, QApplication::UnicodeUTF8));
        pushSettle_38->setText(QApplication::translate("catan_map", "35", 0, QApplication::UnicodeUTF8));
        pushSettle_40->setText(QApplication::translate("catan_map", "556", 0, QApplication::UnicodeUTF8));
        pushSettle_41->setText(QApplication::translate("catan_map", "41", 0, QApplication::UnicodeUTF8));
        pushSettle_43->setText(QApplication::translate("catan_map", "34", 0, QApplication::UnicodeUTF8));
        pushSettle_46->setText(QApplication::translate("catan_map", "46", 0, QApplication::UnicodeUTF8));
        pushSettle_47->setText(QApplication::translate("catan_map", "33", 0, QApplication::UnicodeUTF8));
        pushSettle_39->setText(QApplication::translate("catan_map", "54", 0, QApplication::UnicodeUTF8));
        pushSettle_45->setText(QApplication::translate("catan_map", "42", 0, QApplication::UnicodeUTF8));
        pushSettle_42->setText(QApplication::translate("catan_map", "32", 0, QApplication::UnicodeUTF8));
        pushSettle_44->setText(QApplication::translate("catan_map", "55", 0, QApplication::UnicodeUTF8));
        pushSettle_53->setText(QApplication::translate("catan_map", "44", 0, QApplication::UnicodeUTF8));
        pushSettle_54->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_51->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_50->setText(QApplication::translate("catan_map", "45", 0, QApplication::UnicodeUTF8));
        pushSettle_52->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_48->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushSettle_49->setText(QApplication::translate("catan_map", "43", 0, QApplication::UnicodeUTF8));
        pushRoad_07->setText(QString());
        pushRoad_08->setText(QString());
        pushRoad_34->setText(QString());
        pushRoad_35->setText(QString());
        pushRoad_63->setText(QString());
        pushRoad_36->setText(QString());
        pushRoad_64->setText(QString());
        pushRoad_37->setText(QString());
        pushRoad_65->setText(QString());
        pushRoad_23->setText(QString());
        pushRoad_54->setText(QString());
        pushRoad_39->setText(QString());
        pushRoad_66->setText(QString());
        pushRoad_38->setText(QString());
        pushRoad_10->setText(QString());
        pushRoad_09->setText(QString());
        pushRoad_22->setText(QString());
        pushRoad_53->setText(QString());
        pushRoad_21->setText(QString());
        pushRoad_52->setText(QString());
        pushRoad_51->setText(QString());
        pushRoad_50->setText(QString());
        pushRoad_20->setText(QString());
        pushRoad_19->setText(QString());
        pushRoad_04->setText(QString());
        pushRoad_15->setText(QString());
        pushRoad_16->setText(QString());
        pushRoad_17->setText(QString());
        pushRoad_02->setText(QString());
        pushRoad_06->setText(QString());
        pushRoad_05->setText(QString());
        pushRoad_03->setText(QString());
        pushRoad_01->setText(QString());
        pushRoad_31->setText(QString());
        pushRoad_32->setText(QString());
        pushRoad_18->setText(QString());
        pushRoad_11->setText(QString());
        pushRoad_12->setText(QString());
        pushRoad_13->setText(QString());
        pushRoad_14->setText(QString());
        pushRoad_72->setText(QString());
        pushRoad_56->setText(QString());
        pushRoad_57->setText(QString());
        pushRoad_58->setText(QString());
        pushRoad_59->setText(QString());
        pushRoad_60->setText(QString());
        pushRoad_61->setText(QString());
        pushRoad_67->setText(QString());
        pushRoad_68->setText(QString());
        pushRoad_69->setText(QString());
        pushRoad_70->setText(QString());
        pushRoad_71->setText(QString());
        pushRoad_44->setText(QString());
        pushRoad_45->setText(QString());
        pushRoad_46->setText(QString());
        pushRoad_47->setText(QString());
        pushRoad_48->setText(QString());
        pushRoad_55->setText(QString());
        pushRoad_62->setText(QString());
        pushRoad_28->setText(QString());
        pushRoad_27->setText(QString());
        pushRoad_26->setText(QString());
        pushRoad_25->setText(QString());
        pushRoad_24->setText(QString());
        pushRoad_40->setText(QString());
        pushRoad_41->setText(QString());
        pushRoad_42->setText(QString());
        pushRoad_43->setText(QString());
        pushRoad_33->setText(QString());
        pushRoad_30->setText(QString());
        pushRoad_29->setText(QString());
        pushRoad_49->setText(QString());
        player1_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color1_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts1->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld1_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_01->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        instruction->setText(QApplication::translate("catan_map", "Instruction: Do what this tells you to do!", 0, QApplication::UnicodeUTF8));
        rollButton->setText(QApplication::translate("catan_map", "Roll Dice", 0, QApplication::UnicodeUTF8));
        roll_outcome->setText(QApplication::translate("catan_map", "Current Roll:", 0, QApplication::UnicodeUTF8));
        buyDevButton->setText(QApplication::translate("catan_map", "Buy Development Card", 0, QApplication::UnicodeUTF8));
        player2_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color2_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts2->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld2_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_02->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        player3_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color3_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts3->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld3_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_03->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        player4_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color4_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts4->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld4_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_04->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        menuSample->setTitle(QApplication::translate("catan_map", "Sample", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class catan_map: public Ui_catan_map {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CATAN_MAP_H
