/********************************************************************************
** Form generated from reading UI file 'catan_map.ui'
**
** Created: Tue May 1 15:17:22 2012
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CATAN_MAP_H
#define UI_CATAN_MAP_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_catan_map
{
public:
    QAction *actionWorks;
    QWidget *centralWidget;
    QLabel *image_label;
    QPushButton *pushSettle_223;
    QPushButton *pushSettle_23;
    QPushButton *pushSettle_220;
    QPushButton *pushSettle_221;
    QPushButton *pushSettle_22;
    QPushButton *pushSettle_230;
    QPushButton *pushSettle_330;
    QPushButton *pushSettle_30;
    QPushButton *pushSettle_281;
    QPushButton *pushSettle_33;
    QPushButton *pushSettle_331;
    QPushButton *pushSettle_34;
    QPushButton *pushSettle_334;
    QPushButton *pushSettle_340;
    QPushButton *pushSettle_171;
    QPushButton *pushSettle_12;
    QPushButton *pushSettle_120;
    QPushButton *pushSettle_20;
    QPushButton *pushSettle_440;
    QPushButton *pushSettle_3;
    QPushButton *pushSettle_40;
    QPushButton *pushSettle_391;
    QPushButton *pushSettle_44;
    QPushButton *pushSettle_2;
    QPushButton *pushSettle_4;
    QPushButton *pushSettle_112;
    QPushButton *pushSettle_110;
    QPushButton *pushSettle_111;
    QPushButton *pushSettle_11;
    QPushButton *pushSettle_5;
    QPushButton *pushSettle_1;
    QPushButton *pushSettle_45;
    QPushButton *pushSettle_445;
    QPushButton *pushSettle_441;
    QPushButton *pushSettle_10;
    QPushButton *pushSettle_6;
    QPushButton *pushSettle_50;
    QPushButton *pushSettle_450;
    QPushButton *pushSettle_61;
    QPushButton *pushSettle_60;
    QPushButton *pushSettle_501;
    QPushButton *pushSettle_56;
    QPushButton *pushSettle_550;
    QPushButton *pushSettle_700;
    QPushButton *pushSettle_66;
    QPushButton *pushSettle_55;
    QPushButton *pushSettle_610;
    QPushButton *pushSettle_611;
    QPushButton *pushSettle_556;
    QPushButton *pushSettle_551;
    QPushButton *pushSettle_560;
    QPushButton *pushSettle_666;
    QPushButton *pushSettle_661;
    QPushButton *pushSettle_660;
    QPushButton *pushRoad_07;
    QPushButton *pushRoad_08;
    QPushButton *pushRoad_34;
    QPushButton *pushRoad_35;
    QPushButton *pushRoad_63;
    QPushButton *pushRoad_36;
    QPushButton *pushRoad_64;
    QPushButton *pushRoad_37;
    QPushButton *pushRoad_65;
    QPushButton *pushRoad_23;
    QPushButton *pushRoad_54;
    QPushButton *pushRoad_39;
    QPushButton *pushRoad_66;
    QPushButton *pushRoad_38;
    QPushButton *pushRoad_10;
    QPushButton *pushRoad_09;
    QPushButton *pushRoad_22;
    QPushButton *pushRoad_53;
    QPushButton *pushRoad_21;
    QPushButton *pushRoad_52;
    QPushButton *pushRoad_51;
    QPushButton *pushRoad_50;
    QPushButton *pushRoad_20;
    QPushButton *pushRoad_19;
    QPushButton *pushRoad_04;
    QPushButton *pushRoad_15;
    QPushButton *pushRoad_16;
    QPushButton *pushRoad_17;
    QPushButton *pushRoad_02;
    QPushButton *pushRoad_06;
    QPushButton *pushRoad_05;
    QPushButton *pushRoad_03;
    QPushButton *pushRoad_01;
    QPushButton *pushRoad_31;
    QPushButton *pushRoad_32;
    QPushButton *pushRoad_18;
    QPushButton *pushRoad_11;
    QPushButton *pushRoad_12;
    QPushButton *pushRoad_13;
    QPushButton *pushRoad_14;
    QPushButton *pushRoad_72;
    QPushButton *pushRoad_56;
    QPushButton *pushRoad_57;
    QPushButton *pushRoad_58;
    QPushButton *pushRoad_59;
    QPushButton *pushRoad_60;
    QPushButton *pushRoad_61;
    QPushButton *pushRoad_67;
    QPushButton *pushRoad_68;
    QPushButton *pushRoad_69;
    QPushButton *pushRoad_70;
    QPushButton *pushRoad_71;
    QPushButton *pushRoad_44;
    QPushButton *pushRoad_45;
    QPushButton *pushRoad_46;
    QPushButton *pushRoad_47;
    QPushButton *pushRoad_48;
    QPushButton *pushRoad_55;
    QPushButton *pushRoad_62;
    QPushButton *pushRoad_28;
    QPushButton *pushRoad_27;
    QPushButton *pushRoad_26;
    QPushButton *pushRoad_25;
    QPushButton *pushRoad_24;
    QPushButton *pushRoad_40;
    QPushButton *pushRoad_41;
    QPushButton *pushRoad_42;
    QPushButton *pushRoad_43;
    QPushButton *pushRoad_33;
    QPushButton *pushRoad_30;
    QPushButton *pushRoad_29;
    QPushButton *pushRoad_49;
    QFrame *frame;
    QLabel *player1_label;
    QLabel *color1_label;
    QLabel *victoryPnts1;
    QLabel *cardsHeld1_label;
    QPushButton *vhandButton_01;
    QLabel *instruction;
    QPushButton *rollButton;
    QLabel *roll_outcome;
    QPushButton *buyDevButton;
    QFrame *frame_2;
    QLabel *player2_label;
    QLabel *color2_label;
    QLabel *victoryPnts2;
    QLabel *cardsHeld2_label;
    QPushButton *vhandButton_02;
    QFrame *frame_3;
    QLabel *player3_label;
    QLabel *color3_label;
    QLabel *victoryPnts3;
    QLabel *cardsHeld3_label;
    QPushButton *vhandButton_03;
    QFrame *frame_4;
    QLabel *player4_label;
    QLabel *color4_label;
    QLabel *victoryPnts4;
    QLabel *cardsHeld4_label;
    QPushButton *vhandButton_04;
    QPushButton *node_01;
    QLabel *nstar_01;
    QLabel *nstar_02;
    QPushButton *node_02;
    QPushButton *node_03;
    QLabel *nstar_03;
    QPushButton *node_04;
    QLabel *nstar_04;
    QPushButton *node_05;
    QLabel *nstar_05;
    QPushButton *node_06;
    QLabel *nstar_06;
    QPushButton *node_07;
    QLabel *nstar_07;
    QPushButton *node_08;
    QLabel *nstar_08;
    QPushButton *node_09;
    QLabel *nstar_09;
    QPushButton *node_10;
    QLabel *nstar_10;
    QPushButton *node_11;
    QLabel *nstar_11;
    QPushButton *node_12;
    QLabel *nstar_12;
    QPushButton *node_13;
    QLabel *nstar_13;
    QPushButton *node_14;
    QLabel *nstar_14;
    QPushButton *node_15;
    QLabel *nstar_15;
    QPushButton *node_16;
    QLabel *nstar_16;
    QPushButton *node_17;
    QLabel *nstar_17;
    QPushButton *node_18;
    QLabel *nstar_18;
    QPushButton *node_19;
    QMenuBar *menuBar;
    QMenu *menuSample;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *catan_map)
    {
        if (catan_map->objectName().isEmpty())
            catan_map->setObjectName(QString::fromUtf8("catan_map"));
        catan_map->resize(1000, 703);
        actionWorks = new QAction(catan_map);
        actionWorks->setObjectName(QString::fromUtf8("actionWorks"));
        centralWidget = new QWidget(catan_map);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        image_label = new QLabel(centralWidget);
        image_label->setObjectName(QString::fromUtf8("image_label"));
        image_label->setGeometry(QRect(10, 0, 691, 600));
        pushSettle_223 = new QPushButton(centralWidget);
        pushSettle_223->setObjectName(QString::fromUtf8("pushSettle_223"));
        pushSettle_223->setGeometry(QRect(230, 30, 21, 21));
        pushSettle_23 = new QPushButton(centralWidget);
        pushSettle_23->setObjectName(QString::fromUtf8("pushSettle_23"));
        pushSettle_23->setGeometry(QRect(288, 128, 21, 21));
        pushSettle_220 = new QPushButton(centralWidget);
        pushSettle_220->setObjectName(QString::fromUtf8("pushSettle_220"));
        pushSettle_220->setGeometry(QRect(175, 128, 21, 21));
        pushSettle_221 = new QPushButton(centralWidget);
        pushSettle_221->setObjectName(QString::fromUtf8("pushSettle_221"));
        pushSettle_221->setGeometry(QRect(175, 68, 21, 21));
        pushSettle_22 = new QPushButton(centralWidget);
        pushSettle_22->setObjectName(QString::fromUtf8("pushSettle_22"));
        pushSettle_22->setGeometry(QRect(230, 162, 21, 21));
        pushSettle_230 = new QPushButton(centralWidget);
        pushSettle_230->setObjectName(QString::fromUtf8("pushSettle_230"));
        pushSettle_230->setGeometry(QRect(288, 68, 21, 21));
        pushSettle_330 = new QPushButton(centralWidget);
        pushSettle_330->setObjectName(QString::fromUtf8("pushSettle_330"));
        pushSettle_330->setGeometry(QRect(401, 68, 21, 21));
        pushSettle_30 = new QPushButton(centralWidget);
        pushSettle_30->setObjectName(QString::fromUtf8("pushSettle_30"));
        pushSettle_30->setGeometry(QRect(343, 162, 21, 21));
        pushSettle_281 = new QPushButton(centralWidget);
        pushSettle_281->setObjectName(QString::fromUtf8("pushSettle_281"));
        pushSettle_281->setGeometry(QRect(343, 30, 21, 21));
        pushSettle_33 = new QPushButton(centralWidget);
        pushSettle_33->setObjectName(QString::fromUtf8("pushSettle_33"));
        pushSettle_33->setGeometry(QRect(401, 128, 21, 21));
        pushSettle_331 = new QPushButton(centralWidget);
        pushSettle_331->setObjectName(QString::fromUtf8("pushSettle_331"));
        pushSettle_331->setGeometry(QRect(456, 30, 21, 21));
        pushSettle_34 = new QPushButton(centralWidget);
        pushSettle_34->setObjectName(QString::fromUtf8("pushSettle_34"));
        pushSettle_34->setGeometry(QRect(456, 162, 21, 21));
        pushSettle_334 = new QPushButton(centralWidget);
        pushSettle_334->setObjectName(QString::fromUtf8("pushSettle_334"));
        pushSettle_334->setGeometry(QRect(514, 68, 21, 21));
        pushSettle_340 = new QPushButton(centralWidget);
        pushSettle_340->setObjectName(QString::fromUtf8("pushSettle_340"));
        pushSettle_340->setGeometry(QRect(514, 128, 21, 21));
        pushSettle_171 = new QPushButton(centralWidget);
        pushSettle_171->setObjectName(QString::fromUtf8("pushSettle_171"));
        pushSettle_171->setGeometry(QRect(117, 162, 21, 21));
        pushSettle_12 = new QPushButton(centralWidget);
        pushSettle_12->setObjectName(QString::fromUtf8("pushSettle_12"));
        pushSettle_12->setGeometry(QRect(175, 260, 21, 21));
        pushSettle_120 = new QPushButton(centralWidget);
        pushSettle_120->setObjectName(QString::fromUtf8("pushSettle_120"));
        pushSettle_120->setGeometry(QRect(117, 222, 21, 21));
        pushSettle_20 = new QPushButton(centralWidget);
        pushSettle_20->setObjectName(QString::fromUtf8("pushSettle_20"));
        pushSettle_20->setGeometry(QRect(230, 222, 21, 21));
        pushSettle_440 = new QPushButton(centralWidget);
        pushSettle_440->setObjectName(QString::fromUtf8("pushSettle_440"));
        pushSettle_440->setGeometry(QRect(569, 222, 21, 21));
        pushSettle_3 = new QPushButton(centralWidget);
        pushSettle_3->setObjectName(QString::fromUtf8("pushSettle_3"));
        pushSettle_3->setGeometry(QRect(343, 222, 21, 21));
        pushSettle_40 = new QPushButton(centralWidget);
        pushSettle_40->setObjectName(QString::fromUtf8("pushSettle_40"));
        pushSettle_40->setGeometry(QRect(456, 222, 21, 21));
        pushSettle_391 = new QPushButton(centralWidget);
        pushSettle_391->setObjectName(QString::fromUtf8("pushSettle_391"));
        pushSettle_391->setGeometry(QRect(569, 162, 21, 21));
        pushSettle_44 = new QPushButton(centralWidget);
        pushSettle_44->setObjectName(QString::fromUtf8("pushSettle_44"));
        pushSettle_44->setGeometry(QRect(514, 260, 21, 21));
        pushSettle_2 = new QPushButton(centralWidget);
        pushSettle_2->setObjectName(QString::fromUtf8("pushSettle_2"));
        pushSettle_2->setGeometry(QRect(288, 260, 21, 21));
        pushSettle_4 = new QPushButton(centralWidget);
        pushSettle_4->setObjectName(QString::fromUtf8("pushSettle_4"));
        pushSettle_4->setGeometry(QRect(401, 260, 21, 21));
        pushSettle_112 = new QPushButton(centralWidget);
        pushSettle_112->setObjectName(QString::fromUtf8("pushSettle_112"));
        pushSettle_112->setGeometry(QRect(62, 260, 21, 21));
        pushSettle_110 = new QPushButton(centralWidget);
        pushSettle_110->setObjectName(QString::fromUtf8("pushSettle_110"));
        pushSettle_110->setGeometry(QRect(117, 354, 21, 21));
        pushSettle_111 = new QPushButton(centralWidget);
        pushSettle_111->setObjectName(QString::fromUtf8("pushSettle_111"));
        pushSettle_111->setGeometry(QRect(62, 320, 21, 21));
        pushSettle_11 = new QPushButton(centralWidget);
        pushSettle_11->setObjectName(QString::fromUtf8("pushSettle_11"));
        pushSettle_11->setGeometry(QRect(175, 320, 21, 21));
        pushSettle_5 = new QPushButton(centralWidget);
        pushSettle_5->setObjectName(QString::fromUtf8("pushSettle_5"));
        pushSettle_5->setGeometry(QRect(401, 320, 21, 21));
        pushSettle_1 = new QPushButton(centralWidget);
        pushSettle_1->setObjectName(QString::fromUtf8("pushSettle_1"));
        pushSettle_1->setGeometry(QRect(288, 320, 21, 21));
        pushSettle_45 = new QPushButton(centralWidget);
        pushSettle_45->setObjectName(QString::fromUtf8("pushSettle_45"));
        pushSettle_45->setGeometry(QRect(514, 320, 21, 21));
        pushSettle_445 = new QPushButton(centralWidget);
        pushSettle_445->setObjectName(QString::fromUtf8("pushSettle_445"));
        pushSettle_445->setGeometry(QRect(627, 320, 21, 21));
        pushSettle_441 = new QPushButton(centralWidget);
        pushSettle_441->setObjectName(QString::fromUtf8("pushSettle_441"));
        pushSettle_441->setGeometry(QRect(627, 260, 21, 21));
        pushSettle_10 = new QPushButton(centralWidget);
        pushSettle_10->setObjectName(QString::fromUtf8("pushSettle_10"));
        pushSettle_10->setGeometry(QRect(230, 354, 21, 21));
        pushSettle_6 = new QPushButton(centralWidget);
        pushSettle_6->setObjectName(QString::fromUtf8("pushSettle_6"));
        pushSettle_6->setGeometry(QRect(343, 354, 21, 21));
        pushSettle_50 = new QPushButton(centralWidget);
        pushSettle_50->setObjectName(QString::fromUtf8("pushSettle_50"));
        pushSettle_50->setGeometry(QRect(456, 354, 21, 21));
        pushSettle_450 = new QPushButton(centralWidget);
        pushSettle_450->setObjectName(QString::fromUtf8("pushSettle_450"));
        pushSettle_450->setGeometry(QRect(569, 354, 21, 21));
        pushSettle_61 = new QPushButton(centralWidget);
        pushSettle_61->setObjectName(QString::fromUtf8("pushSettle_61"));
        pushSettle_61->setGeometry(QRect(230, 414, 21, 21));
        pushSettle_60 = new QPushButton(centralWidget);
        pushSettle_60->setObjectName(QString::fromUtf8("pushSettle_60"));
        pushSettle_60->setGeometry(QRect(343, 414, 21, 21));
        pushSettle_501 = new QPushButton(centralWidget);
        pushSettle_501->setObjectName(QString::fromUtf8("pushSettle_501"));
        pushSettle_501->setGeometry(QRect(569, 414, 21, 21));
        pushSettle_56 = new QPushButton(centralWidget);
        pushSettle_56->setObjectName(QString::fromUtf8("pushSettle_56"));
        pushSettle_56->setGeometry(QRect(401, 452, 21, 21));
        pushSettle_550 = new QPushButton(centralWidget);
        pushSettle_550->setObjectName(QString::fromUtf8("pushSettle_550"));
        pushSettle_550->setGeometry(QRect(514, 452, 21, 21));
        pushSettle_700 = new QPushButton(centralWidget);
        pushSettle_700->setObjectName(QString::fromUtf8("pushSettle_700"));
        pushSettle_700->setGeometry(QRect(117, 414, 21, 21));
        pushSettle_66 = new QPushButton(centralWidget);
        pushSettle_66->setObjectName(QString::fromUtf8("pushSettle_66"));
        pushSettle_66->setGeometry(QRect(288, 452, 21, 21));
        pushSettle_55 = new QPushButton(centralWidget);
        pushSettle_55->setObjectName(QString::fromUtf8("pushSettle_55"));
        pushSettle_55->setGeometry(QRect(456, 414, 21, 21));
        pushSettle_610 = new QPushButton(centralWidget);
        pushSettle_610->setObjectName(QString::fromUtf8("pushSettle_610"));
        pushSettle_610->setGeometry(QRect(175, 452, 21, 21));
        pushSettle_611 = new QPushButton(centralWidget);
        pushSettle_611->setObjectName(QString::fromUtf8("pushSettle_611"));
        pushSettle_611->setGeometry(QRect(343, 546, 21, 21));
        pushSettle_556 = new QPushButton(centralWidget);
        pushSettle_556->setObjectName(QString::fromUtf8("pushSettle_556"));
        pushSettle_556->setGeometry(QRect(456, 546, 21, 21));
        pushSettle_551 = new QPushButton(centralWidget);
        pushSettle_551->setObjectName(QString::fromUtf8("pushSettle_551"));
        pushSettle_551->setGeometry(QRect(514, 512, 21, 21));
        pushSettle_560 = new QPushButton(centralWidget);
        pushSettle_560->setObjectName(QString::fromUtf8("pushSettle_560"));
        pushSettle_560->setGeometry(QRect(401, 512, 21, 21));
        pushSettle_666 = new QPushButton(centralWidget);
        pushSettle_666->setObjectName(QString::fromUtf8("pushSettle_666"));
        pushSettle_666->setGeometry(QRect(230, 546, 21, 21));
        pushSettle_661 = new QPushButton(centralWidget);
        pushSettle_661->setObjectName(QString::fromUtf8("pushSettle_661"));
        pushSettle_661->setGeometry(QRect(175, 512, 21, 21));
        pushSettle_660 = new QPushButton(centralWidget);
        pushSettle_660->setObjectName(QString::fromUtf8("pushSettle_660"));
        pushSettle_660->setGeometry(QRect(288, 512, 21, 21));
        pushRoad_07 = new QPushButton(centralWidget);
        pushRoad_07->setObjectName(QString::fromUtf8("pushRoad_07"));
        pushRoad_07->setGeometry(QRect(175, 93, 21, 31));
        pushRoad_08 = new QPushButton(centralWidget);
        pushRoad_08->setObjectName(QString::fromUtf8("pushRoad_08"));
        pushRoad_08->setGeometry(QRect(288, 93, 21, 31));
        pushRoad_34 = new QPushButton(centralWidget);
        pushRoad_34->setObjectName(QString::fromUtf8("pushRoad_34"));
        pushRoad_34->setGeometry(QRect(62, 285, 21, 31));
        pushRoad_35 = new QPushButton(centralWidget);
        pushRoad_35->setObjectName(QString::fromUtf8("pushRoad_35"));
        pushRoad_35->setGeometry(QRect(175, 285, 21, 31));
        pushRoad_63 = new QPushButton(centralWidget);
        pushRoad_63->setObjectName(QString::fromUtf8("pushRoad_63"));
        pushRoad_63->setGeometry(QRect(175, 477, 21, 31));
        pushRoad_36 = new QPushButton(centralWidget);
        pushRoad_36->setObjectName(QString::fromUtf8("pushRoad_36"));
        pushRoad_36->setGeometry(QRect(288, 285, 21, 31));
        pushRoad_64 = new QPushButton(centralWidget);
        pushRoad_64->setObjectName(QString::fromUtf8("pushRoad_64"));
        pushRoad_64->setGeometry(QRect(288, 477, 21, 31));
        pushRoad_37 = new QPushButton(centralWidget);
        pushRoad_37->setObjectName(QString::fromUtf8("pushRoad_37"));
        pushRoad_37->setGeometry(QRect(401, 285, 21, 31));
        pushRoad_65 = new QPushButton(centralWidget);
        pushRoad_65->setObjectName(QString::fromUtf8("pushRoad_65"));
        pushRoad_65->setGeometry(QRect(401, 477, 21, 31));
        pushRoad_23 = new QPushButton(centralWidget);
        pushRoad_23->setObjectName(QString::fromUtf8("pushRoad_23"));
        pushRoad_23->setGeometry(QRect(569, 185, 21, 31));
        pushRoad_54 = new QPushButton(centralWidget);
        pushRoad_54->setObjectName(QString::fromUtf8("pushRoad_54"));
        pushRoad_54->setGeometry(QRect(569, 379, 21, 31));
        pushRoad_39 = new QPushButton(centralWidget);
        pushRoad_39->setObjectName(QString::fromUtf8("pushRoad_39"));
        pushRoad_39->setGeometry(QRect(627, 285, 21, 31));
        pushRoad_66 = new QPushButton(centralWidget);
        pushRoad_66->setObjectName(QString::fromUtf8("pushRoad_66"));
        pushRoad_66->setGeometry(QRect(514, 477, 21, 31));
        pushRoad_38 = new QPushButton(centralWidget);
        pushRoad_38->setObjectName(QString::fromUtf8("pushRoad_38"));
        pushRoad_38->setGeometry(QRect(514, 285, 21, 31));
        pushRoad_10 = new QPushButton(centralWidget);
        pushRoad_10->setObjectName(QString::fromUtf8("pushRoad_10"));
        pushRoad_10->setGeometry(QRect(514, 93, 21, 31));
        pushRoad_09 = new QPushButton(centralWidget);
        pushRoad_09->setObjectName(QString::fromUtf8("pushRoad_09"));
        pushRoad_09->setGeometry(QRect(401, 93, 21, 31));
        pushRoad_22 = new QPushButton(centralWidget);
        pushRoad_22->setObjectName(QString::fromUtf8("pushRoad_22"));
        pushRoad_22->setGeometry(QRect(456, 185, 21, 31));
        pushRoad_53 = new QPushButton(centralWidget);
        pushRoad_53->setObjectName(QString::fromUtf8("pushRoad_53"));
        pushRoad_53->setGeometry(QRect(456, 379, 21, 31));
        pushRoad_21 = new QPushButton(centralWidget);
        pushRoad_21->setObjectName(QString::fromUtf8("pushRoad_21"));
        pushRoad_21->setGeometry(QRect(343, 185, 21, 31));
        pushRoad_52 = new QPushButton(centralWidget);
        pushRoad_52->setObjectName(QString::fromUtf8("pushRoad_52"));
        pushRoad_52->setGeometry(QRect(343, 379, 21, 31));
        pushRoad_51 = new QPushButton(centralWidget);
        pushRoad_51->setObjectName(QString::fromUtf8("pushRoad_51"));
        pushRoad_51->setGeometry(QRect(230, 379, 21, 31));
        pushRoad_50 = new QPushButton(centralWidget);
        pushRoad_50->setObjectName(QString::fromUtf8("pushRoad_50"));
        pushRoad_50->setGeometry(QRect(117, 379, 21, 31));
        pushRoad_20 = new QPushButton(centralWidget);
        pushRoad_20->setObjectName(QString::fromUtf8("pushRoad_20"));
        pushRoad_20->setGeometry(QRect(230, 185, 21, 31));
        pushRoad_19 = new QPushButton(centralWidget);
        pushRoad_19->setObjectName(QString::fromUtf8("pushRoad_19"));
        pushRoad_19->setGeometry(QRect(117, 185, 21, 31));
        pushRoad_04 = new QPushButton(centralWidget);
        pushRoad_04->setObjectName(QString::fromUtf8("pushRoad_04"));
        pushRoad_04->setGeometry(QRect(373, 43, 21, 31));
        pushRoad_15 = new QPushButton(centralWidget);
        pushRoad_15->setObjectName(QString::fromUtf8("pushRoad_15"));
        pushRoad_15->setGeometry(QRect(373, 141, 21, 31));
        pushRoad_16 = new QPushButton(centralWidget);
        pushRoad_16->setObjectName(QString::fromUtf8("pushRoad_16"));
        pushRoad_16->setGeometry(QRect(426, 141, 21, 31));
        pushRoad_17 = new QPushButton(centralWidget);
        pushRoad_17->setObjectName(QString::fromUtf8("pushRoad_17"));
        pushRoad_17->setGeometry(QRect(486, 141, 21, 31));
        pushRoad_02 = new QPushButton(centralWidget);
        pushRoad_02->setObjectName(QString::fromUtf8("pushRoad_02"));
        pushRoad_02->setGeometry(QRect(260, 43, 21, 31));
        pushRoad_06 = new QPushButton(centralWidget);
        pushRoad_06->setObjectName(QString::fromUtf8("pushRoad_06"));
        pushRoad_06->setGeometry(QRect(486, 43, 21, 31));
        pushRoad_05 = new QPushButton(centralWidget);
        pushRoad_05->setObjectName(QString::fromUtf8("pushRoad_05"));
        pushRoad_05->setGeometry(QRect(426, 43, 21, 31));
        pushRoad_03 = new QPushButton(centralWidget);
        pushRoad_03->setObjectName(QString::fromUtf8("pushRoad_03"));
        pushRoad_03->setGeometry(QRect(313, 43, 21, 31));
        pushRoad_01 = new QPushButton(centralWidget);
        pushRoad_01->setObjectName(QString::fromUtf8("pushRoad_01"));
        pushRoad_01->setGeometry(QRect(200, 43, 21, 31));
        pushRoad_31 = new QPushButton(centralWidget);
        pushRoad_31->setObjectName(QString::fromUtf8("pushRoad_31"));
        pushRoad_31->setGeometry(QRect(486, 235, 21, 31));
        pushRoad_32 = new QPushButton(centralWidget);
        pushRoad_32->setObjectName(QString::fromUtf8("pushRoad_32"));
        pushRoad_32->setGeometry(QRect(544, 235, 21, 31));
        pushRoad_18 = new QPushButton(centralWidget);
        pushRoad_18->setObjectName(QString::fromUtf8("pushRoad_18"));
        pushRoad_18->setGeometry(QRect(544, 141, 21, 31));
        pushRoad_11 = new QPushButton(centralWidget);
        pushRoad_11->setObjectName(QString::fromUtf8("pushRoad_11"));
        pushRoad_11->setGeometry(QRect(145, 141, 21, 31));
        pushRoad_12 = new QPushButton(centralWidget);
        pushRoad_12->setObjectName(QString::fromUtf8("pushRoad_12"));
        pushRoad_12->setGeometry(QRect(200, 141, 21, 31));
        pushRoad_13 = new QPushButton(centralWidget);
        pushRoad_13->setObjectName(QString::fromUtf8("pushRoad_13"));
        pushRoad_13->setGeometry(QRect(260, 141, 21, 31));
        pushRoad_14 = new QPushButton(centralWidget);
        pushRoad_14->setObjectName(QString::fromUtf8("pushRoad_14"));
        pushRoad_14->setGeometry(QRect(313, 141, 21, 31));
        pushRoad_72 = new QPushButton(centralWidget);
        pushRoad_72->setObjectName(QString::fromUtf8("pushRoad_72"));
        pushRoad_72->setGeometry(QRect(486, 525, 21, 31));
        pushRoad_56 = new QPushButton(centralWidget);
        pushRoad_56->setObjectName(QString::fromUtf8("pushRoad_56"));
        pushRoad_56->setGeometry(QRect(200, 427, 21, 31));
        pushRoad_57 = new QPushButton(centralWidget);
        pushRoad_57->setObjectName(QString::fromUtf8("pushRoad_57"));
        pushRoad_57->setGeometry(QRect(260, 427, 21, 31));
        pushRoad_58 = new QPushButton(centralWidget);
        pushRoad_58->setObjectName(QString::fromUtf8("pushRoad_58"));
        pushRoad_58->setGeometry(QRect(313, 427, 21, 31));
        pushRoad_59 = new QPushButton(centralWidget);
        pushRoad_59->setObjectName(QString::fromUtf8("pushRoad_59"));
        pushRoad_59->setGeometry(QRect(373, 427, 21, 31));
        pushRoad_60 = new QPushButton(centralWidget);
        pushRoad_60->setObjectName(QString::fromUtf8("pushRoad_60"));
        pushRoad_60->setGeometry(QRect(426, 427, 21, 31));
        pushRoad_61 = new QPushButton(centralWidget);
        pushRoad_61->setObjectName(QString::fromUtf8("pushRoad_61"));
        pushRoad_61->setGeometry(QRect(486, 427, 21, 31));
        pushRoad_67 = new QPushButton(centralWidget);
        pushRoad_67->setObjectName(QString::fromUtf8("pushRoad_67"));
        pushRoad_67->setGeometry(QRect(200, 525, 21, 31));
        pushRoad_68 = new QPushButton(centralWidget);
        pushRoad_68->setObjectName(QString::fromUtf8("pushRoad_68"));
        pushRoad_68->setGeometry(QRect(260, 525, 21, 31));
        pushRoad_69 = new QPushButton(centralWidget);
        pushRoad_69->setObjectName(QString::fromUtf8("pushRoad_69"));
        pushRoad_69->setGeometry(QRect(313, 525, 21, 31));
        pushRoad_70 = new QPushButton(centralWidget);
        pushRoad_70->setObjectName(QString::fromUtf8("pushRoad_70"));
        pushRoad_70->setGeometry(QRect(373, 525, 21, 31));
        pushRoad_71 = new QPushButton(centralWidget);
        pushRoad_71->setObjectName(QString::fromUtf8("pushRoad_71"));
        pushRoad_71->setGeometry(QRect(426, 525, 21, 31));
        pushRoad_44 = new QPushButton(centralWidget);
        pushRoad_44->setObjectName(QString::fromUtf8("pushRoad_44"));
        pushRoad_44->setGeometry(QRect(313, 333, 21, 31));
        pushRoad_45 = new QPushButton(centralWidget);
        pushRoad_45->setObjectName(QString::fromUtf8("pushRoad_45"));
        pushRoad_45->setGeometry(QRect(373, 333, 21, 31));
        pushRoad_46 = new QPushButton(centralWidget);
        pushRoad_46->setObjectName(QString::fromUtf8("pushRoad_46"));
        pushRoad_46->setGeometry(QRect(426, 333, 21, 31));
        pushRoad_47 = new QPushButton(centralWidget);
        pushRoad_47->setObjectName(QString::fromUtf8("pushRoad_47"));
        pushRoad_47->setGeometry(QRect(486, 333, 21, 31));
        pushRoad_48 = new QPushButton(centralWidget);
        pushRoad_48->setObjectName(QString::fromUtf8("pushRoad_48"));
        pushRoad_48->setGeometry(QRect(544, 333, 21, 31));
        pushRoad_55 = new QPushButton(centralWidget);
        pushRoad_55->setObjectName(QString::fromUtf8("pushRoad_55"));
        pushRoad_55->setGeometry(QRect(145, 427, 21, 31));
        pushRoad_62 = new QPushButton(centralWidget);
        pushRoad_62->setObjectName(QString::fromUtf8("pushRoad_62"));
        pushRoad_62->setGeometry(QRect(544, 427, 21, 31));
        pushRoad_28 = new QPushButton(centralWidget);
        pushRoad_28->setObjectName(QString::fromUtf8("pushRoad_28"));
        pushRoad_28->setGeometry(QRect(313, 235, 21, 31));
        pushRoad_27 = new QPushButton(centralWidget);
        pushRoad_27->setObjectName(QString::fromUtf8("pushRoad_27"));
        pushRoad_27->setGeometry(QRect(260, 235, 21, 31));
        pushRoad_26 = new QPushButton(centralWidget);
        pushRoad_26->setObjectName(QString::fromUtf8("pushRoad_26"));
        pushRoad_26->setGeometry(QRect(200, 235, 21, 31));
        pushRoad_25 = new QPushButton(centralWidget);
        pushRoad_25->setObjectName(QString::fromUtf8("pushRoad_25"));
        pushRoad_25->setGeometry(QRect(145, 235, 21, 31));
        pushRoad_24 = new QPushButton(centralWidget);
        pushRoad_24->setObjectName(QString::fromUtf8("pushRoad_24"));
        pushRoad_24->setGeometry(QRect(87, 235, 21, 31));
        pushRoad_40 = new QPushButton(centralWidget);
        pushRoad_40->setObjectName(QString::fromUtf8("pushRoad_40"));
        pushRoad_40->setGeometry(QRect(87, 333, 21, 31));
        pushRoad_41 = new QPushButton(centralWidget);
        pushRoad_41->setObjectName(QString::fromUtf8("pushRoad_41"));
        pushRoad_41->setGeometry(QRect(145, 333, 21, 31));
        pushRoad_42 = new QPushButton(centralWidget);
        pushRoad_42->setObjectName(QString::fromUtf8("pushRoad_42"));
        pushRoad_42->setGeometry(QRect(200, 333, 21, 31));
        pushRoad_43 = new QPushButton(centralWidget);
        pushRoad_43->setObjectName(QString::fromUtf8("pushRoad_43"));
        pushRoad_43->setGeometry(QRect(260, 333, 21, 31));
        pushRoad_33 = new QPushButton(centralWidget);
        pushRoad_33->setObjectName(QString::fromUtf8("pushRoad_33"));
        pushRoad_33->setGeometry(QRect(599, 235, 21, 31));
        pushRoad_30 = new QPushButton(centralWidget);
        pushRoad_30->setObjectName(QString::fromUtf8("pushRoad_30"));
        pushRoad_30->setGeometry(QRect(426, 235, 21, 31));
        pushRoad_29 = new QPushButton(centralWidget);
        pushRoad_29->setObjectName(QString::fromUtf8("pushRoad_29"));
        pushRoad_29->setGeometry(QRect(373, 235, 21, 31));
        pushRoad_49 = new QPushButton(centralWidget);
        pushRoad_49->setObjectName(QString::fromUtf8("pushRoad_49"));
        pushRoad_49->setGeometry(QRect(599, 330, 21, 31));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(710, 3, 281, 141));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        player1_label = new QLabel(frame);
        player1_label->setObjectName(QString::fromUtf8("player1_label"));
        player1_label->setGeometry(QRect(10, 10, 101, 17));
        QFont font;
        font.setPointSize(16);
        player1_label->setFont(font);
        color1_label = new QLabel(frame);
        color1_label->setObjectName(QString::fromUtf8("color1_label"));
        color1_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts1 = new QLabel(frame);
        victoryPnts1->setObjectName(QString::fromUtf8("victoryPnts1"));
        victoryPnts1->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld1_label = new QLabel(frame);
        cardsHeld1_label->setObjectName(QString::fromUtf8("cardsHeld1_label"));
        cardsHeld1_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_01 = new QPushButton(frame);
        vhandButton_01->setObjectName(QString::fromUtf8("vhandButton_01"));
        vhandButton_01->setGeometry(QRect(60, 40, 131, 51));
        instruction = new QLabel(centralWidget);
        instruction->setObjectName(QString::fromUtf8("instruction"));
        instruction->setGeometry(QRect(40, 610, 601, 17));
        rollButton = new QPushButton(centralWidget);
        rollButton->setObjectName(QString::fromUtf8("rollButton"));
        rollButton->setGeometry(QRect(890, 604, 97, 27));
        roll_outcome = new QLabel(centralWidget);
        roll_outcome->setObjectName(QString::fromUtf8("roll_outcome"));
        roll_outcome->setGeometry(QRect(790, 610, 91, 17));
        buyDevButton = new QPushButton(centralWidget);
        buyDevButton->setObjectName(QString::fromUtf8("buyDevButton"));
        buyDevButton->setGeometry(QRect(610, 604, 171, 27));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(710, 150, 281, 141));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        player2_label = new QLabel(frame_2);
        player2_label->setObjectName(QString::fromUtf8("player2_label"));
        player2_label->setGeometry(QRect(10, 10, 101, 17));
        player2_label->setFont(font);
        color2_label = new QLabel(frame_2);
        color2_label->setObjectName(QString::fromUtf8("color2_label"));
        color2_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts2 = new QLabel(frame_2);
        victoryPnts2->setObjectName(QString::fromUtf8("victoryPnts2"));
        victoryPnts2->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld2_label = new QLabel(frame_2);
        cardsHeld2_label->setObjectName(QString::fromUtf8("cardsHeld2_label"));
        cardsHeld2_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_02 = new QPushButton(frame_2);
        vhandButton_02->setObjectName(QString::fromUtf8("vhandButton_02"));
        vhandButton_02->setGeometry(QRect(60, 40, 131, 51));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(710, 300, 281, 141));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        player3_label = new QLabel(frame_3);
        player3_label->setObjectName(QString::fromUtf8("player3_label"));
        player3_label->setGeometry(QRect(10, 10, 101, 17));
        player3_label->setFont(font);
        color3_label = new QLabel(frame_3);
        color3_label->setObjectName(QString::fromUtf8("color3_label"));
        color3_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts3 = new QLabel(frame_3);
        victoryPnts3->setObjectName(QString::fromUtf8("victoryPnts3"));
        victoryPnts3->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld3_label = new QLabel(frame_3);
        cardsHeld3_label->setObjectName(QString::fromUtf8("cardsHeld3_label"));
        cardsHeld3_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_03 = new QPushButton(frame_3);
        vhandButton_03->setObjectName(QString::fromUtf8("vhandButton_03"));
        vhandButton_03->setGeometry(QRect(60, 40, 131, 51));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(710, 450, 281, 141));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        player4_label = new QLabel(frame_4);
        player4_label->setObjectName(QString::fromUtf8("player4_label"));
        player4_label->setGeometry(QRect(10, 10, 101, 17));
        player4_label->setFont(font);
        color4_label = new QLabel(frame_4);
        color4_label->setObjectName(QString::fromUtf8("color4_label"));
        color4_label->setGeometry(QRect(150, 10, 67, 17));
        victoryPnts4 = new QLabel(frame_4);
        victoryPnts4->setObjectName(QString::fromUtf8("victoryPnts4"));
        victoryPnts4->setGeometry(QRect(10, 120, 131, 17));
        cardsHeld4_label = new QLabel(frame_4);
        cardsHeld4_label->setObjectName(QString::fromUtf8("cardsHeld4_label"));
        cardsHeld4_label->setGeometry(QRect(10, 100, 121, 17));
        vhandButton_04 = new QPushButton(frame_4);
        vhandButton_04->setObjectName(QString::fromUtf8("vhandButton_04"));
        vhandButton_04->setGeometry(QRect(60, 40, 131, 51));
        node_01 = new QPushButton(centralWidget);
        node_01->setObjectName(QString::fromUtf8("node_01"));
        node_01->setGeometry(QRect(220, 85, 41, 41));
        nstar_01 = new QLabel(centralWidget);
        nstar_01->setObjectName(QString::fromUtf8("nstar_01"));
        nstar_01->setGeometry(QRect(220, 110, 41, 16));
        nstar_01->setAlignment(Qt::AlignCenter);
        nstar_02 = new QLabel(centralWidget);
        nstar_02->setObjectName(QString::fromUtf8("nstar_02"));
        nstar_02->setGeometry(QRect(323, 110, 61, 16));
        nstar_02->setAlignment(Qt::AlignCenter);
        node_02 = new QPushButton(centralWidget);
        node_02->setObjectName(QString::fromUtf8("node_02"));
        node_02->setGeometry(QRect(333, 85, 41, 41));
        node_03 = new QPushButton(centralWidget);
        node_03->setObjectName(QString::fromUtf8("node_03"));
        node_03->setGeometry(QRect(446, 85, 41, 41));
        nstar_03 = new QLabel(centralWidget);
        nstar_03->setObjectName(QString::fromUtf8("nstar_03"));
        nstar_03->setGeometry(QRect(436, 110, 61, 16));
        nstar_03->setAlignment(Qt::AlignCenter);
        node_04 = new QPushButton(centralWidget);
        node_04->setObjectName(QString::fromUtf8("node_04"));
        node_04->setGeometry(QRect(164, 180, 41, 41));
        nstar_04 = new QLabel(centralWidget);
        nstar_04->setObjectName(QString::fromUtf8("nstar_04"));
        nstar_04->setGeometry(QRect(154, 205, 61, 16));
        nstar_04->setAlignment(Qt::AlignCenter);
        node_05 = new QPushButton(centralWidget);
        node_05->setObjectName(QString::fromUtf8("node_05"));
        node_05->setGeometry(QRect(277, 180, 41, 41));
        nstar_05 = new QLabel(centralWidget);
        nstar_05->setObjectName(QString::fromUtf8("nstar_05"));
        nstar_05->setGeometry(QRect(267, 205, 61, 16));
        nstar_05->setAlignment(Qt::AlignCenter);
        node_06 = new QPushButton(centralWidget);
        node_06->setObjectName(QString::fromUtf8("node_06"));
        node_06->setGeometry(QRect(390, 180, 41, 41));
        nstar_06 = new QLabel(centralWidget);
        nstar_06->setObjectName(QString::fromUtf8("nstar_06"));
        nstar_06->setGeometry(QRect(380, 205, 61, 16));
        nstar_06->setAlignment(Qt::AlignCenter);
        node_07 = new QPushButton(centralWidget);
        node_07->setObjectName(QString::fromUtf8("node_07"));
        node_07->setGeometry(QRect(503, 180, 41, 41));
        nstar_07 = new QLabel(centralWidget);
        nstar_07->setObjectName(QString::fromUtf8("nstar_07"));
        nstar_07->setGeometry(QRect(494, 205, 61, 16));
        nstar_07->setAlignment(Qt::AlignCenter);
        node_08 = new QPushButton(centralWidget);
        node_08->setObjectName(QString::fromUtf8("node_08"));
        node_08->setGeometry(QRect(220, 275, 41, 41));
        nstar_08 = new QLabel(centralWidget);
        nstar_08->setObjectName(QString::fromUtf8("nstar_08"));
        nstar_08->setGeometry(QRect(210, 300, 61, 16));
        nstar_08->setAlignment(Qt::AlignCenter);
        node_09 = new QPushButton(centralWidget);
        node_09->setObjectName(QString::fromUtf8("node_09"));
        node_09->setGeometry(QRect(333, 275, 41, 41));
        nstar_09 = new QLabel(centralWidget);
        nstar_09->setObjectName(QString::fromUtf8("nstar_09"));
        nstar_09->setGeometry(QRect(323, 300, 61, 16));
        nstar_09->setAlignment(Qt::AlignCenter);
        node_10 = new QPushButton(centralWidget);
        node_10->setObjectName(QString::fromUtf8("node_10"));
        node_10->setGeometry(QRect(446, 275, 41, 41));
        nstar_10 = new QLabel(centralWidget);
        nstar_10->setObjectName(QString::fromUtf8("nstar_10"));
        nstar_10->setGeometry(QRect(437, 300, 61, 16));
        nstar_10->setAlignment(Qt::AlignCenter);
        node_11 = new QPushButton(centralWidget);
        node_11->setObjectName(QString::fromUtf8("node_11"));
        node_11->setGeometry(QRect(559, 275, 41, 41));
        nstar_11 = new QLabel(centralWidget);
        nstar_11->setObjectName(QString::fromUtf8("nstar_11"));
        nstar_11->setGeometry(QRect(549, 300, 61, 16));
        nstar_11->setAlignment(Qt::AlignCenter);
        node_12 = new QPushButton(centralWidget);
        node_12->setObjectName(QString::fromUtf8("node_12"));
        node_12->setGeometry(QRect(164, 370, 41, 41));
        nstar_12 = new QLabel(centralWidget);
        nstar_12->setObjectName(QString::fromUtf8("nstar_12"));
        nstar_12->setGeometry(QRect(155, 395, 61, 16));
        nstar_12->setAlignment(Qt::AlignCenter);
        node_13 = new QPushButton(centralWidget);
        node_13->setObjectName(QString::fromUtf8("node_13"));
        node_13->setGeometry(QRect(277, 370, 41, 41));
        nstar_13 = new QLabel(centralWidget);
        nstar_13->setObjectName(QString::fromUtf8("nstar_13"));
        nstar_13->setGeometry(QRect(268, 395, 61, 16));
        nstar_13->setAlignment(Qt::AlignCenter);
        node_14 = new QPushButton(centralWidget);
        node_14->setObjectName(QString::fromUtf8("node_14"));
        node_14->setGeometry(QRect(390, 370, 41, 41));
        nstar_14 = new QLabel(centralWidget);
        nstar_14->setObjectName(QString::fromUtf8("nstar_14"));
        nstar_14->setGeometry(QRect(380, 395, 61, 16));
        nstar_14->setAlignment(Qt::AlignCenter);
        node_15 = new QPushButton(centralWidget);
        node_15->setObjectName(QString::fromUtf8("node_15"));
        node_15->setGeometry(QRect(503, 370, 41, 41));
        nstar_15 = new QLabel(centralWidget);
        nstar_15->setObjectName(QString::fromUtf8("nstar_15"));
        nstar_15->setGeometry(QRect(493, 395, 61, 16));
        nstar_15->setAlignment(Qt::AlignCenter);
        node_16 = new QPushButton(centralWidget);
        node_16->setObjectName(QString::fromUtf8("node_16"));
        node_16->setGeometry(QRect(220, 470, 41, 41));
        nstar_16 = new QLabel(centralWidget);
        nstar_16->setObjectName(QString::fromUtf8("nstar_16"));
        nstar_16->setGeometry(QRect(210, 496, 61, 16));
        nstar_16->setAlignment(Qt::AlignCenter);
        node_17 = new QPushButton(centralWidget);
        node_17->setObjectName(QString::fromUtf8("node_17"));
        node_17->setGeometry(QRect(333, 470, 41, 41));
        nstar_17 = new QLabel(centralWidget);
        nstar_17->setObjectName(QString::fromUtf8("nstar_17"));
        nstar_17->setGeometry(QRect(323, 496, 61, 16));
        nstar_17->setAlignment(Qt::AlignCenter);
        node_18 = new QPushButton(centralWidget);
        node_18->setObjectName(QString::fromUtf8("node_18"));
        node_18->setGeometry(QRect(446, 470, 41, 41));
        nstar_18 = new QLabel(centralWidget);
        nstar_18->setObjectName(QString::fromUtf8("nstar_18"));
        nstar_18->setGeometry(QRect(436, 496, 61, 16));
        nstar_18->setAlignment(Qt::AlignCenter);
        node_19 = new QPushButton(centralWidget);
        node_19->setObjectName(QString::fromUtf8("node_19"));
        node_19->setGeometry(QRect(105, 275, 41, 41));
        catan_map->setCentralWidget(centralWidget);
        image_label->raise();
        pushSettle_223->raise();
        pushSettle_23->raise();
        pushSettle_220->raise();
        pushSettle_221->raise();
        pushSettle_22->raise();
        pushSettle_230->raise();
        pushSettle_330->raise();
        pushSettle_30->raise();
        pushSettle_281->raise();
        pushSettle_33->raise();
        pushSettle_331->raise();
        pushSettle_34->raise();
        pushSettle_334->raise();
        pushSettle_340->raise();
        pushSettle_171->raise();
        pushSettle_12->raise();
        pushSettle_120->raise();
        pushSettle_20->raise();
        pushSettle_440->raise();
        pushSettle_3->raise();
        pushSettle_40->raise();
        pushSettle_391->raise();
        pushSettle_44->raise();
        pushSettle_2->raise();
        pushSettle_4->raise();
        pushSettle_112->raise();
        pushSettle_110->raise();
        pushSettle_111->raise();
        pushSettle_11->raise();
        pushSettle_5->raise();
        pushSettle_1->raise();
        pushSettle_45->raise();
        pushSettle_445->raise();
        pushSettle_441->raise();
        pushSettle_10->raise();
        pushSettle_6->raise();
        pushSettle_50->raise();
        pushSettle_450->raise();
        pushSettle_61->raise();
        pushSettle_60->raise();
        pushSettle_501->raise();
        pushSettle_56->raise();
        pushSettle_550->raise();
        pushSettle_700->raise();
        pushSettle_66->raise();
        pushSettle_55->raise();
        pushSettle_610->raise();
        pushSettle_611->raise();
        pushSettle_556->raise();
        pushSettle_551->raise();
        pushSettle_560->raise();
        pushSettle_666->raise();
        pushSettle_661->raise();
        pushSettle_660->raise();
        pushRoad_07->raise();
        pushRoad_08->raise();
        pushRoad_34->raise();
        pushRoad_35->raise();
        pushRoad_63->raise();
        pushRoad_36->raise();
        pushRoad_64->raise();
        pushRoad_37->raise();
        pushRoad_65->raise();
        pushRoad_23->raise();
        pushRoad_54->raise();
        pushRoad_39->raise();
        pushRoad_66->raise();
        pushRoad_38->raise();
        pushRoad_10->raise();
        pushRoad_09->raise();
        pushRoad_22->raise();
        pushRoad_53->raise();
        pushRoad_21->raise();
        pushRoad_52->raise();
        pushRoad_51->raise();
        pushRoad_50->raise();
        pushRoad_20->raise();
        pushRoad_19->raise();
        pushRoad_04->raise();
        pushRoad_15->raise();
        pushRoad_16->raise();
        pushRoad_17->raise();
        pushRoad_02->raise();
        pushRoad_06->raise();
        pushRoad_05->raise();
        pushRoad_03->raise();
        pushRoad_01->raise();
        pushRoad_31->raise();
        pushRoad_32->raise();
        pushRoad_18->raise();
        pushRoad_11->raise();
        pushRoad_12->raise();
        pushRoad_13->raise();
        pushRoad_14->raise();
        pushRoad_72->raise();
        pushRoad_56->raise();
        pushRoad_57->raise();
        pushRoad_58->raise();
        pushRoad_59->raise();
        pushRoad_60->raise();
        pushRoad_61->raise();
        pushRoad_67->raise();
        pushRoad_68->raise();
        pushRoad_69->raise();
        pushRoad_70->raise();
        pushRoad_71->raise();
        pushRoad_44->raise();
        pushRoad_45->raise();
        pushRoad_46->raise();
        pushRoad_47->raise();
        pushRoad_48->raise();
        pushRoad_55->raise();
        pushRoad_62->raise();
        pushRoad_28->raise();
        pushRoad_27->raise();
        pushRoad_26->raise();
        pushRoad_25->raise();
        pushRoad_24->raise();
        pushRoad_40->raise();
        pushRoad_41->raise();
        pushRoad_42->raise();
        pushRoad_43->raise();
        pushRoad_33->raise();
        pushRoad_30->raise();
        pushRoad_29->raise();
        pushRoad_49->raise();
        frame->raise();
        instruction->raise();
        rollButton->raise();
        roll_outcome->raise();
        buyDevButton->raise();
        frame_2->raise();
        frame_3->raise();
        frame_4->raise();
        node_01->raise();
        nstar_01->raise();
        node_02->raise();
        nstar_02->raise();
        node_03->raise();
        nstar_03->raise();
        node_04->raise();
        nstar_04->raise();
        node_05->raise();
        nstar_05->raise();
        node_06->raise();
        nstar_06->raise();
        node_07->raise();
        nstar_07->raise();
        node_08->raise();
        nstar_08->raise();
        node_09->raise();
        nstar_09->raise();
        node_10->raise();
        nstar_10->raise();
        node_11->raise();
        nstar_11->raise();
        node_12->raise();
        nstar_12->raise();
        node_13->raise();
        nstar_13->raise();
        node_14->raise();
        nstar_14->raise();
        node_15->raise();
        nstar_15->raise();
        node_16->raise();
        nstar_16->raise();
        node_17->raise();
        nstar_17->raise();
        node_18->raise();
        nstar_18->raise();
        node_19->raise();
        menuBar = new QMenuBar(catan_map);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1000, 26));
        menuSample = new QMenu(menuBar);
        menuSample->setObjectName(QString::fromUtf8("menuSample"));
        catan_map->setMenuBar(menuBar);
        mainToolBar = new QToolBar(catan_map);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        catan_map->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(catan_map);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        catan_map->setStatusBar(statusBar);

        menuBar->addAction(menuSample->menuAction());
        menuSample->addAction(actionWorks);

        retranslateUi(catan_map);

        QMetaObject::connectSlotsByName(catan_map);
    } // setupUi

    void retranslateUi(QMainWindow *catan_map)
    {
        catan_map->setWindowTitle(QApplication::translate("catan_map", "catan_map", 0, QApplication::UnicodeUTF8));
        actionWorks->setText(QApplication::translate("catan_map", "Works!!", 0, QApplication::UnicodeUTF8));
        image_label->setText(QString());
        pushSettle_223->setText(QString());
        pushSettle_23->setText(QString());
        pushSettle_220->setText(QString());
        pushSettle_221->setText(QString());
        pushSettle_22->setText(QString());
        pushSettle_230->setText(QString());
        pushSettle_330->setText(QString());
        pushSettle_30->setText(QString());
        pushSettle_281->setText(QString());
        pushSettle_33->setText(QString());
        pushSettle_331->setText(QString());
        pushSettle_34->setText(QString());
        pushSettle_334->setText(QString());
        pushSettle_340->setText(QString());
        pushSettle_171->setText(QString());
        pushSettle_12->setText(QString());
        pushSettle_120->setText(QString());
        pushSettle_20->setText(QString());
        pushSettle_440->setText(QString());
        pushSettle_3->setText(QString());
        pushSettle_40->setText(QString());
        pushSettle_391->setText(QString());
        pushSettle_44->setText(QString());
        pushSettle_2->setText(QString());
        pushSettle_4->setText(QString());
        pushSettle_112->setText(QString());
        pushSettle_110->setText(QString());
        pushSettle_111->setText(QString());
        pushSettle_11->setText(QString());
        pushSettle_5->setText(QString());
        pushSettle_1->setText(QString());
        pushSettle_45->setText(QString());
        pushSettle_445->setText(QString());
        pushSettle_441->setText(QString());
        pushSettle_10->setText(QString());
        pushSettle_6->setText(QString());
        pushSettle_50->setText(QString());
        pushSettle_450->setText(QString());
        pushSettle_61->setText(QString());
        pushSettle_60->setText(QString());
        pushSettle_501->setText(QString());
        pushSettle_56->setText(QString());
        pushSettle_550->setText(QString());
        pushSettle_700->setText(QString());
        pushSettle_66->setText(QString());
        pushSettle_55->setText(QString());
        pushSettle_610->setText(QString());
        pushSettle_611->setText(QString());
        pushSettle_556->setText(QString());
        pushSettle_551->setText(QString());
        pushSettle_560->setText(QString());
        pushSettle_666->setText(QString());
        pushSettle_661->setText(QString());
        pushSettle_660->setText(QString());
        pushRoad_07->setText(QString());
        pushRoad_08->setText(QString());
        pushRoad_34->setText(QString());
        pushRoad_35->setText(QString());
        pushRoad_63->setText(QString());
        pushRoad_36->setText(QString());
        pushRoad_64->setText(QString());
        pushRoad_37->setText(QString());
        pushRoad_65->setText(QString());
        pushRoad_23->setText(QString());
        pushRoad_54->setText(QString());
        pushRoad_39->setText(QString());
        pushRoad_66->setText(QString());
        pushRoad_38->setText(QString());
        pushRoad_10->setText(QString());
        pushRoad_09->setText(QString());
        pushRoad_22->setText(QString());
        pushRoad_53->setText(QString());
        pushRoad_21->setText(QString());
        pushRoad_52->setText(QString());
        pushRoad_51->setText(QString());
        pushRoad_50->setText(QString());
        pushRoad_20->setText(QString());
        pushRoad_19->setText(QString());
        pushRoad_04->setText(QString());
        pushRoad_15->setText(QString());
        pushRoad_16->setText(QString());
        pushRoad_17->setText(QString());
        pushRoad_02->setText(QString());
        pushRoad_06->setText(QString());
        pushRoad_05->setText(QString());
        pushRoad_03->setText(QString());
        pushRoad_01->setText(QString());
        pushRoad_31->setText(QString());
        pushRoad_32->setText(QString());
        pushRoad_18->setText(QString());
        pushRoad_11->setText(QString());
        pushRoad_12->setText(QString());
        pushRoad_13->setText(QString());
        pushRoad_14->setText(QString());
        pushRoad_72->setText(QString());
        pushRoad_56->setText(QString());
        pushRoad_57->setText(QString());
        pushRoad_58->setText(QString());
        pushRoad_59->setText(QString());
        pushRoad_60->setText(QString());
        pushRoad_61->setText(QString());
        pushRoad_67->setText(QString());
        pushRoad_68->setText(QString());
        pushRoad_69->setText(QString());
        pushRoad_70->setText(QString());
        pushRoad_71->setText(QString());
        pushRoad_44->setText(QString());
        pushRoad_45->setText(QString());
        pushRoad_46->setText(QString());
        pushRoad_47->setText(QString());
        pushRoad_48->setText(QString());
        pushRoad_55->setText(QString());
        pushRoad_62->setText(QString());
        pushRoad_28->setText(QString());
        pushRoad_27->setText(QString());
        pushRoad_26->setText(QString());
        pushRoad_25->setText(QString());
        pushRoad_24->setText(QString());
        pushRoad_40->setText(QString());
        pushRoad_41->setText(QString());
        pushRoad_42->setText(QString());
        pushRoad_43->setText(QString());
        pushRoad_33->setText(QString());
        pushRoad_30->setText(QString());
        pushRoad_29->setText(QString());
        pushRoad_49->setText(QString());
        player1_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color1_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts1->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld1_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_01->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        instruction->setText(QApplication::translate("catan_map", "Instruction: Do what this tells you to do!", 0, QApplication::UnicodeUTF8));
        rollButton->setText(QApplication::translate("catan_map", "Roll Dice", 0, QApplication::UnicodeUTF8));
        roll_outcome->setText(QApplication::translate("catan_map", "Current Roll:", 0, QApplication::UnicodeUTF8));
        buyDevButton->setText(QApplication::translate("catan_map", "Buy Development Card", 0, QApplication::UnicodeUTF8));
        player2_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color2_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts2->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld2_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_02->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        player3_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color3_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts3->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld3_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_03->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        player4_label->setText(QApplication::translate("catan_map", "Player 1", 0, QApplication::UnicodeUTF8));
        color4_label->setText(QApplication::translate("catan_map", "Color", 0, QApplication::UnicodeUTF8));
        victoryPnts4->setText(QApplication::translate("catan_map", "Victory Points:", 0, QApplication::UnicodeUTF8));
        cardsHeld4_label->setText(QApplication::translate("catan_map", "Cards Held:", 0, QApplication::UnicodeUTF8));
        vhandButton_04->setText(QApplication::translate("catan_map", "View Hand", 0, QApplication::UnicodeUTF8));
        node_01->setText(QApplication::translate("catan_map", "11", 0, QApplication::UnicodeUTF8));
        nstar_01->setText(QApplication::translate("catan_map", "**", 0, QApplication::UnicodeUTF8));
        nstar_02->setText(QApplication::translate("catan_map", "*", 0, QApplication::UnicodeUTF8));
        node_02->setText(QApplication::translate("catan_map", "12", 0, QApplication::UnicodeUTF8));
        node_03->setText(QApplication::translate("catan_map", "9", 0, QApplication::UnicodeUTF8));
        nstar_03->setText(QApplication::translate("catan_map", "****", 0, QApplication::UnicodeUTF8));
        node_04->setText(QApplication::translate("catan_map", "4", 0, QApplication::UnicodeUTF8));
        nstar_04->setText(QApplication::translate("catan_map", "***", 0, QApplication::UnicodeUTF8));
        node_05->setText(QApplication::translate("catan_map", "6", 0, QApplication::UnicodeUTF8));
        nstar_05->setText(QApplication::translate("catan_map", "****", 0, QApplication::UnicodeUTF8));
        node_06->setText(QApplication::translate("catan_map", "5", 0, QApplication::UnicodeUTF8));
        nstar_06->setText(QApplication::translate("catan_map", "****", 0, QApplication::UnicodeUTF8));
        node_07->setText(QApplication::translate("catan_map", "10", 0, QApplication::UnicodeUTF8));
        nstar_07->setText(QApplication::translate("catan_map", "***", 0, QApplication::UnicodeUTF8));
        node_08->setText(QApplication::translate("catan_map", "3", 0, QApplication::UnicodeUTF8));
        nstar_08->setText(QApplication::translate("catan_map", "**", 0, QApplication::UnicodeUTF8));
        node_09->setText(QApplication::translate("catan_map", "11", 0, QApplication::UnicodeUTF8));
        nstar_09->setText(QApplication::translate("catan_map", "**", 0, QApplication::UnicodeUTF8));
        node_10->setText(QApplication::translate("catan_map", "4", 0, QApplication::UnicodeUTF8));
        nstar_10->setText(QApplication::translate("catan_map", "***", 0, QApplication::UnicodeUTF8));
        node_11->setText(QApplication::translate("catan_map", "8", 0, QApplication::UnicodeUTF8));
        nstar_11->setText(QApplication::translate("catan_map", "*****", 0, QApplication::UnicodeUTF8));
        node_12->setText(QApplication::translate("catan_map", "8", 0, QApplication::UnicodeUTF8));
        nstar_12->setText(QApplication::translate("catan_map", "*****", 0, QApplication::UnicodeUTF8));
        node_13->setText(QApplication::translate("catan_map", "10", 0, QApplication::UnicodeUTF8));
        nstar_13->setText(QApplication::translate("catan_map", "***", 0, QApplication::UnicodeUTF8));
        node_14->setText(QApplication::translate("catan_map", "9", 0, QApplication::UnicodeUTF8));
        nstar_14->setText(QApplication::translate("catan_map", "****", 0, QApplication::UnicodeUTF8));
        node_15->setText(QApplication::translate("catan_map", "3", 0, QApplication::UnicodeUTF8));
        nstar_15->setText(QApplication::translate("catan_map", "**", 0, QApplication::UnicodeUTF8));
        node_16->setText(QApplication::translate("catan_map", "5", 0, QApplication::UnicodeUTF8));
        nstar_16->setText(QApplication::translate("catan_map", "****", 0, QApplication::UnicodeUTF8));
        node_17->setText(QApplication::translate("catan_map", "2", 0, QApplication::UnicodeUTF8));
        nstar_17->setText(QApplication::translate("catan_map", "*", 0, QApplication::UnicodeUTF8));
        node_18->setText(QApplication::translate("catan_map", "6", 0, QApplication::UnicodeUTF8));
        nstar_18->setText(QApplication::translate("catan_map", "*****", 0, QApplication::UnicodeUTF8));
        node_19->setText(QString());
        menuSample->setTitle(QApplication::translate("catan_map", "Sample", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class catan_map: public Ui_catan_map {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CATAN_MAP_H
