######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 22 21:10:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Player.h
SOURCES += Catan.cpp Catan_Main.cpp
